#!/usr/bin/env Rscript
# Ives tip-error correction for PGLS
# Estimates lambda_B with measurement error via phytools::phylosig,
# then re-runs PGLS with corrected lambda.
#
# Uses: data/ives_se_joined.csv (generated by ives_correction_se_compute.py)
# Out:  data/ives_correction_results.csv

suppressMessages({
  library(ape)
  library(nlme)
  library(caper)
  library(phytools)
})

DATA <- "projects/comprehensive_metal_ecology/data"
SCRIPTS <- "projects/comprehensive_metal_ecology/scripts"

cat("Loading data...\n")
df <- read.csv(file.path(DATA, "ives_se_joined.csv"), stringsAsFactors = FALSE)
cat(sprintf("  Genera: %d\n", nrow(df)))
cat(sprintf("  Genera with SE: %d\n", sum(!is.na(df$se_levins_B))))

# Load and prune tree
tree <- read.tree(file.path(DATA, "gtdb_bac_genus_pruned.tree"))
in_tree <- df$genus_lower[df$genus_lower %in% tree$tip.label]
tree_pruned <- drop.tip(tree, setdiff(tree$tip.label, in_tree))
df <- df[df$genus_lower %in% tree_pruned$tip.label, ]
df <- df[match(tree_pruned$tip.label, df$genus_lower), ]
cat(sprintf("  After tree match: %d genera\n", nrow(df)))

# Subset to genera with SE (for phylosig with SE)
df_se <- df[!is.na(df$se_levins_B), ]
tree_se <- drop.tip(tree_pruned, setdiff(tree_pruned$tip.label, df_se$genus_lower))
df_se <- df_se[match(tree_se$tip.label, df_se$genus_lower), ]
cat(sprintf("  Genera with SE for phylosig: %d\n", nrow(df_se)))

# ── 1. Phylogenetic signal of Levins' B without SE correction ─────────────────
cat("\n1. Phylosig WITHOUT SE correction...\n")
trait <- df_se$mean_levins_B_std
names(trait) <- df_se$genus_lower
ps_no_se <- phylosig(tree_se, trait, method = "lambda", test = TRUE)
cat(sprintf("   lambda_B_raw = %.4f  (logL-ratio test p = %.4f)\n",
            ps_no_se$lambda, ps_no_se$P))

# ── 2. Phylogenetic signal of Levins' B WITH SE correction ──────────────────
cat("\n2. Phylosig WITH SE (Ives tip-error correction)...\n")
se_vec <- df_se$se_levins_B
names(se_vec) <- df_se$genus_lower
tryCatch({
  ps_se <- phylosig(tree_se, trait, method = "lambda", se = se_vec, test = TRUE)
  cat(sprintf("   lambda_B_corrected = %.4f  (logL-ratio test p = %.4f)\n",
              ps_se$lambda, ps_se$P))
  lambda_ives <- ps_se$lambda
  lambda_ives_p <- ps_se$P
}, error = function(e) {
  cat(sprintf("   phytools phylosig with SE failed: %s\n", e$message))
  lambda_ives <<- NA
  lambda_ives_p <<- NA
})

# ── 3. Re-run PGLS with Ives-corrected lambda for Levins' B ─────────────────
cat("\n3. PGLS with Ives-corrected lambda...\n")

# Prepare log(n_ko) response
# The PGLS input uses ko_per_mb_primary; need to reconstruct n_ko
# n_ko = ko_per_mb * mean_genome_mb
df_se$log_nko <- log(df_se$ko_per_mb_primary * df_se$mean_genome_mb)
df_se$B_z <- scale(df_se$mean_levins_B_std)[,1]
df_se$log_genome <- log(df_se$mean_genome_mb)

# Standard PGLS (Pagel lambda)
cd_se <- comparative.data(tree_se, df_se, genus_lower, vcv = TRUE)

fit_pagel <- tryCatch(
  pgls(log_nko ~ B_z + log_genome, data = cd_se, lambda = "ML"),
  error = function(e) { cat("Pagel PGLS failed:", e$message, "\n"); NULL }
)

if (!is.null(fit_pagel)) {
  coefs_pagel <- summary(fit_pagel)$coefficients
  cat(sprintf("   Pagel PGLS (subset n=%d): lambda=%.4f  beta_B=%.4f p=%.4f\n",
              nrow(df_se), fit_pagel$param["lambda"],
              coefs_pagel["B_z", "Estimate"],
              coefs_pagel["B_z", "Pr(>|t|)"]))
}

# Ives-corrected PGLS (lambda fixed at lambda_ives)
fit_ives_pgls <- tryCatch({
  if (!is.na(lambda_ives)) {
    pgls(log_nko ~ B_z + log_genome, data = cd_se, lambda = lambda_ives)
  } else NULL
}, error = function(e) { cat("Ives PGLS failed:", e$message, "\n"); NULL })

if (!is.null(fit_ives_pgls)) {
  coefs_ives <- summary(fit_ives_pgls)$coefficients
  cat(sprintf("   Ives PGLS (lambda=%.4f): beta_B=%.4f p=%.4f\n",
              lambda_ives,
              coefs_ives["B_z", "Estimate"],
              coefs_ives["B_z", "Pr(>|t|)"]))
}

# ── 4. Simulation: add B measurement error and re-run PGLS ─────────────────
cat("\n4. Simulation: add B measurement error and re-run PGLS (n_sim=100)...\n")
n_sim <- 100
beta_sim <- numeric(n_sim)
df_full <- df[match(tree_pruned$tip.label, df$genus_lower), ]
df_full$log_nko <- log(df_full$ko_per_mb_primary * df_full$mean_genome_mb)
df_full$B_z_raw <- df_full$mean_levins_B_std
df_full$log_genome <- log(df_full$mean_genome_mb)

# Use median SE where SE is missing
median_se <- median(df_se$se_levins_B, na.rm = TRUE)
df_full$se_levins_B[is.na(df_full$se_levins_B)] <- median_se

set.seed(42)
cd_full <- comparative.data(tree_pruned, df_full, genus_lower, vcv = TRUE)

for (i in seq_len(n_sim)) {
  # Add noise to Levins' B
  df_full$B_noisy <- df_full$B_z_raw +
    rnorm(nrow(df_full), 0, df_full$se_levins_B)
  # Standardize noisy B
  df_full$B_z <- scale(df_full$B_noisy)[,1]

  tryCatch({
    cd_sim <- comparative.data(tree_pruned, df_full, genus_lower, vcv = TRUE)
    fit_sim <- pgls(log_nko ~ B_z + log_genome, data = cd_sim, lambda = "ML")
    beta_sim[i] <- summary(fit_sim)$coefficients["B_z", "Estimate"]
  }, error = function(e) {
    beta_sim[i] <<- NA
  })
  if (i %% 100 == 0) cat(sprintf("   sim %d / %d...\n", i, n_sim))
}

beta_sim <- beta_sim[!is.na(beta_sim)]
cat(sprintf("   Simulation beta_B: mean=%.4f SD=%.4f CI=[%.4f, %.4f]\n",
            mean(beta_sim), sd(beta_sim),
            quantile(beta_sim, 0.025), quantile(beta_sim, 0.975)))
cat(sprintf("   Fraction of sims with beta_B < 0: %.3f\n",
            mean(beta_sim < 0)))

# ── 5. Save results ─────────────────────────────────────────────────────────
results <- data.frame(
  analysis = c("phylosig_raw", "phylosig_ives_corrected",
                "pgls_pagel_subset", "pgls_ives_fixed",
                "simulation_mean", "simulation_sd",
                "simulation_ci_lo", "simulation_ci_hi",
                "simulation_pct_negative"),
  value = c(
    ps_no_se$lambda, lambda_ives,
    if (!is.null(fit_pagel)) coefs_pagel["B_z", "Estimate"] else NA,
    if (!is.null(fit_ives_pgls)) coefs_ives["B_z", "Estimate"] else NA,
    mean(beta_sim), sd(beta_sim),
    quantile(beta_sim, 0.025), quantile(beta_sim, 0.975),
    mean(beta_sim < 0)
  ),
  p_value = c(
    ps_no_se$P, lambda_ives_p,
    if (!is.null(fit_pagel)) coefs_pagel["B_z", "Pr(>|t|)"] else NA,
    if (!is.null(fit_ives_pgls)) coefs_ives["B_z", "Pr(>|t|)"] else NA,
    rep(NA, 5)
  )
)

write.csv(results,
          file.path(DATA, "ives_correction_results.csv"),
          row.names = FALSE)
cat("\nSaved -> data/ives_correction_results.csv\n")
