"""
Build figS1_sample_overview.pdf — multi-panel dataset overview figure.

Panels:
  A  Sample counts by biome (horizontal bar, log-x)
  B  World map of sample locations coloured by biome
  C  Genus prevalence distribution with >=10 threshold
  D  Phylum composition of the 1,574 primary-analysis genera
  E  MicrobeAtlas niche breadth (B_std) distribution
  F  EMP prevalence vs EMP niche breadth (detection-bias check)
  G  t-SNE of 25k stratified MicrobeAtlas samples, coloured by biome
     (from data/tsne_embedding.csv, generated by compute_tsne_embedding.py)
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch
import numpy as np
import pandas as pd
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data'
FIG  = ROOT / 'figures'

# ── load ──────────────────────────────────────────────────────────────────────
sdf = pd.read_csv(DATA / 'sample_latlon_env.csv')
sdf['lat'] = pd.to_numeric(sdf['LatitudeParsed'], errors='coerce')
sdf['lon'] = pd.to_numeric(sdf['LongitudeParsed'], errors='coerce')

gdf = pd.read_csv(DATA / 'genus_microbeatlas_sample_counts.csv')
pdf = pd.read_csv(DATA / '01_pgls_input_bacteria.csv')
edf = pd.read_csv(DATA / 'emp_niche_pgls_input.csv')
tdf = pd.read_csv(DATA / 'tsne_embedding.csv')

# ── biome grouping ─────────────────────────────────────────────────────────
SMALL = {'desert', 'paddy', 'peatland', 'leaf', 'shrub', 'flower'}
sdf['biome'] = sdf['Env_Level_1'].apply(lambda x: 'other' if x in SMALL else x)

BIOME_ORDER = ['aquatic', 'soil', 'plant', 'forest', 'field',
               'agricultural', 'farm', 'other']
BIOME_LABELS = {
    'aquatic': 'Aquatic', 'soil': 'Soil', 'plant': 'Plant',
    'forest': 'Forest', 'field': 'Field', 'agricultural': 'Agricultural',
    'farm': 'Farm', 'other': 'Other',
}
BIOME_COLORS = {
    'aquatic':      '#4E9FD4',
    'soil':         '#8B5E3C',
    'plant':        '#5AAA5F',
    'forest':       '#2E7D32',
    'field':        '#A8C96F',
    'agricultural': '#F4A261',
    'farm':         '#D9B99B',
    'other':        '#AAAAAA',
}

# normalise any biome labels not in BIOME_ORDER (e.g. 'unknown') → 'other'
tdf['biome'] = tdf['biome'].apply(
    lambda x: x if x in BIOME_COLORS else 'other'
)

# ── valid geo subset ───────────────────────────────────────────────────────
geo = sdf[(sdf.lat >= -90) & (sdf.lat <= 90) &
          (sdf.lon >= -180) & (sdf.lon <= 180)].copy()

MAP_N = 60_000
rng = np.random.default_rng(42)
parts = []
for biome, grp in geo.groupby('biome'):
    n = max(1, int(MAP_N * len(grp) / len(geo)))
    idx = rng.choice(len(grp), min(n, len(grp)), replace=False)
    parts.append(grp.iloc[idx])
geo_samp = pd.concat(parts, ignore_index=True)

# ── figure layout: 3 rows × 3 cols, row 2 full-width for t-SNE ─────────────
fig = plt.figure(figsize=(18, 14))
fig.patch.set_facecolor('white')
gs = gridspec.GridSpec(
    3, 3, figure=fig,
    hspace=0.50, wspace=0.38,
    left=0.07, right=0.97, top=0.96, bottom=0.05,
    height_ratios=[1, 1, 0.85],
)

ax_a = fig.add_subplot(gs[0, 0])
ax_b = fig.add_subplot(gs[0, 1], projection=ccrs.Robinson())
ax_c = fig.add_subplot(gs[0, 2])
ax_d = fig.add_subplot(gs[1, 0])
ax_e = fig.add_subplot(gs[1, 1])
ax_f = fig.add_subplot(gs[1, 2])
ax_g = fig.add_subplot(gs[2, :])          # t-SNE spans all three columns

LABEL_KW = dict(fontsize=13, fontweight='bold', loc='left', pad=4)


# ══════════════════════════════════════════════════════════════════════════════
# PANEL A — sample counts by biome
# ══════════════════════════════════════════════════════════════════════════════
bc = sdf['biome'].value_counts()
bc = bc.reindex([b for b in BIOME_ORDER if b in bc.index])
colors_a = [BIOME_COLORS[b] for b in bc.index]
y_labels  = [BIOME_LABELS[b] for b in bc.index]

bars = ax_a.barh(y_labels, bc.values, color=colors_a, height=0.65,
                 edgecolor='white', linewidth=0.5)
ax_a.set_xscale('log')
ax_a.set_xlabel('Number of samples', fontsize=9)
ax_a.set_title('a', **LABEL_KW)
ax_a.tick_params(labelsize=8)
ax_a.spines[['top', 'right']].set_visible(False)
for bar, val in zip(bars, bc.values):
    ax_a.text(val * 1.12, bar.get_y() + bar.get_height() / 2,
              f'{val:,}', va='center', ha='left', fontsize=7)
ax_a.set_xlim(right=ax_a.get_xlim()[1] * 4)
ax_a.set_xlim(left=100)
ax_a.text(0.97, 0.03, f'Total: {len(sdf):,}', transform=ax_a.transAxes,
          ha='right', va='bottom', fontsize=7, color='#555')


# ══════════════════════════════════════════════════════════════════════════════
# PANEL B — world map
# ══════════════════════════════════════════════════════════════════════════════
ax_b.set_global()
ax_b.add_feature(cfeature.LAND,      facecolor='#F0EDE6', zorder=0)
ax_b.add_feature(cfeature.OCEAN,     facecolor='#E4F0F7', zorder=0)
ax_b.add_feature(cfeature.COASTLINE, linewidth=0.3, edgecolor='#888', zorder=1)
ax_b.add_feature(cfeature.BORDERS,   linewidth=0.15, linestyle=':',
                 edgecolor='#AAA', zorder=1)

plot_order = ['other', 'farm', 'agricultural', 'field', 'forest',
              'plant', 'soil', 'aquatic']
for biome in plot_order:
    grp = geo_samp[geo_samp['biome'] == biome]
    if len(grp) == 0:
        continue
    ax_b.scatter(grp.lon, grp.lat, c=BIOME_COLORS[biome],
                 s=0.8, alpha=0.5, transform=ccrs.PlateCarree(),
                 rasterized=True, zorder=2)

ax_b.set_title('b', **LABEL_KW)
ax_b.gridlines(draw_labels=False, linewidth=0.2, color='gray', alpha=0.4)

legend_handles = [
    Patch(facecolor=BIOME_COLORS[b], label=BIOME_LABELS[b], edgecolor='white')
    for b in BIOME_ORDER
]
ax_b.legend(handles=legend_handles, loc='lower left', fontsize=6.5,
            frameon=True, framealpha=0.85, ncol=2,
            borderpad=0.5, labelspacing=0.25, columnspacing=0.7,
            handlelength=1.0, handleheight=0.9)


# ══════════════════════════════════════════════════════════════════════════════
# PANEL C — genus prevalence distribution
# ══════════════════════════════════════════════════════════════════════════════
log_prev = np.log10(gdf['n_samples'].clip(lower=1).values)
n_above = (gdf['n_samples'] >= 10).sum()
n_total = len(gdf)
ax_c.hist(log_prev, bins=45, color='#5B8DB8', edgecolor='white', linewidth=0.3)
ax_c.axvline(np.log10(10), color='#D62728', linestyle='--', linewidth=1.3,
             label=f'≥10-sample threshold\n({n_above:,}/{n_total:,} genera)')
ax_c.set_xlabel('Samples detected (log$_{10}$)', fontsize=9)
ax_c.set_ylabel('Number of genera', fontsize=9)
ax_c.set_title('c', **LABEL_KW)
ax_c.legend(fontsize=7, frameon=False)
ax_c.spines[['top', 'right']].set_visible(False)
ax_c.tick_params(labelsize=8)
xticks = [0, 1, 2, 3, 4, 5]
ax_c.set_xticks(xticks)
ax_c.set_xticklabels([f'$10^{{{x}}}$' for x in xticks], fontsize=7.5)


# ══════════════════════════════════════════════════════════════════════════════
# PANEL D — phylum composition of primary genera
# ══════════════════════════════════════════════════════════════════════════════
ph = pdf['phylum'].value_counts()
top_n = 9
top_ph = ph.head(top_n)
other_ph = ph.iloc[top_n:].sum()
ph_plot = pd.concat([pd.Series({'Other': other_ph}), top_ph]).sort_values()

tab10 = plt.cm.tab10.colors
ph_colors = [tab10[i % 10] for i in range(len(ph_plot))]

ax_d.barh(ph_plot.index, ph_plot.values, color=ph_colors, height=0.65,
          edgecolor='white', linewidth=0.4)
ax_d.set_xlabel('Number of genera', fontsize=9)
ax_d.set_title('d', **LABEL_KW)
ax_d.tick_params(axis='y', labelsize=7.5)
ax_d.tick_params(axis='x', labelsize=8)
ax_d.spines[['top', 'right']].set_visible(False)
for i, (idx, val) in enumerate(ph_plot.items()):
    ax_d.text(val + 5, i, str(val), va='center', ha='left', fontsize=7)
ax_d.set_xlim(right=ph_plot.max() * 1.25)
ax_d.text(0.97, 0.03, f'n = {len(pdf):,} genera', transform=ax_d.transAxes,
          ha='right', va='bottom', fontsize=7, color='#555')


# ══════════════════════════════════════════════════════════════════════════════
# PANEL E — MicrobeAtlas niche breadth distribution
# ══════════════════════════════════════════════════════════════════════════════
bstd = pdf['mean_levins_B_std'].dropna()
med = bstd.median()
ax_e.hist(bstd, bins=45, color='#6CA88A', edgecolor='white', linewidth=0.3)
ax_e.axvline(med, color='#222', linestyle='--', linewidth=1.1,
             label=f'Median = {med:.2f}')
ax_e.set_xlabel(r"Levins' $B_\mathrm{std}$ (MicrobeAtlas)", fontsize=9)
ax_e.set_ylabel('Number of genera', fontsize=9)
ax_e.set_title('e', **LABEL_KW)
ax_e.legend(fontsize=7.5, frameon=False)
ax_e.spines[['top', 'right']].set_visible(False)
ax_e.tick_params(labelsize=8)
ax_e.text(0.97, 0.97, f'n = {len(bstd):,}', transform=ax_e.transAxes,
          ha='right', va='top', fontsize=7, color='#555')


# ══════════════════════════════════════════════════════════════════════════════
# PANEL F — EMP prevalence vs EMP niche breadth
# ══════════════════════════════════════════════════════════════════════════════
ef = edf[['n_samples_total', 'emp_levins_B_std']].dropna()
log_emp = np.log10(ef['n_samples_total'].clip(lower=1))

ax_f.scatter(log_emp, ef['emp_levins_B_std'],
             alpha=0.35, s=12, color='#9467BD', rasterized=True)

n_bins = 10
bins = np.percentile(log_emp, np.linspace(0, 100, n_bins + 1))
bx, by = [], []
for i in range(n_bins):
    mask = (log_emp >= bins[i]) & (log_emp < bins[i + 1])
    if mask.sum() >= 3:
        bx.append((bins[i] + bins[i + 1]) / 2)
        by.append(ef['emp_levins_B_std'][mask].mean())
ax_f.plot(bx, by, color='#D62728', linewidth=1.6, zorder=3, label='Binned mean')

ax_f.set_xlabel('EMP prevalence (log$_{10}$ samples)', fontsize=9)
ax_f.set_ylabel(r"EMP Levins' $B_\mathrm{std}$", fontsize=9)
ax_f.set_title('f', **LABEL_KW)
ax_f.legend(fontsize=7, frameon=False)
ax_f.spines[['top', 'right']].set_visible(False)
ax_f.tick_params(labelsize=8)
xticks_f = [1, 2]
ax_f.set_xticks(xticks_f)
ax_f.set_xticklabels([f'$10^{{{x}}}$' for x in xticks_f], fontsize=8)
ax_f.text(0.97, 0.03, f'n = {len(ef):,}', transform=ax_f.transAxes,
          ha='right', va='bottom', fontsize=7, color='#555')


# ══════════════════════════════════════════════════════════════════════════════
# PANEL G — t-SNE of MicrobeAtlas samples coloured by biome
# ══════════════════════════════════════════════════════════════════════════════
# Plot order: dense biomes first so sparse ones are visible on top
tsne_plot_order = ['aquatic', 'farm', 'agricultural', 'field', 'forest',
                   'plant', 'soil', 'other']
for biome in tsne_plot_order:
    grp = tdf[tdf['biome'] == biome]
    if len(grp) == 0:
        continue
    ax_g.scatter(
        grp['tsne_x'], grp['tsne_y'],
        c=BIOME_COLORS.get(biome, '#AAAAAA'),
        s=2, alpha=0.5, rasterized=True,
        label=BIOME_LABELS.get(biome, biome.capitalize()),
    )

ax_g.set_xlabel('t-SNE 1', fontsize=9)
ax_g.set_ylabel('t-SNE 2', fontsize=9)
ax_g.set_title('g', **LABEL_KW)
ax_g.spines[['top', 'right']].set_visible(False)
ax_g.tick_params(labelsize=8)
ax_g.set_aspect('equal', adjustable='datalim')
ax_g.text(
    0.01, 0.99,
    f'n = {len(tdf):,} samples (stratified)\n'
    f'TruncSVD 50 PCs → t-SNE (perplexity = 50)',
    transform=ax_g.transAxes, ha='left', va='top',
    fontsize=7, color='#555',
)

# legend with larger markers for readability
leg_handles = [
    plt.scatter([], [], c=BIOME_COLORS.get(b, '#AAAAAA'), s=20,
                label=BIOME_LABELS.get(b, b.capitalize()))
    for b in BIOME_ORDER if b in tdf['biome'].values
]
ax_g.legend(
    handles=leg_handles, loc='upper right', fontsize=7,
    frameon=True, framealpha=0.85, ncol=4,
    borderpad=0.5, labelspacing=0.3, columnspacing=0.8,
    handletextpad=0.3,
)

# ── save ───────────────────────────────────────────────────────────────────
out_pdf = FIG / 'figS1_sample_overview.pdf'
out_png = FIG / 'png' / 'figS1_sample_overview.png'

fig.savefig(out_pdf, dpi=200, bbox_inches='tight', facecolor='white')
fig.savefig(out_png, dpi=150, bbox_inches='tight', facecolor='white')
print(f'Saved {out_pdf}')
print(f'Saved {out_png}')
