from _build import build_and_run

cells = [
    ("md", "# NB02b — Deepening Phase-1 Pathway Linkage\n\n"
           "NB02 left **21 of 83 compounds dark** (no measured fitness, no ModelSEED "
           "reaction, no KEGG id, no literature term-hit) — concentrated in methylated "
           "quinolinones/quinolines (alkaloids), chromones/chalcones (shikimates/"
           "polyketides), and bicyclic terpenoids. That dark set is a **headline result** "
           "(a quantified knowledge gap for NP secondary metabolites) and is preserved "
           "intact here.\n\n"
           "This notebook tries to *claw back* additional linkage **before** organism "
           "mapping, using three channels that look past the curated-database bias:\n\n"
           "- **A. KEGG REST deepening** — for the 54 KEGG-bearing compounds, replace the "
           "weak `has_kegg` flag with **real reactions** and, critically, **degradation-"
           "pathway membership** (KEGG `link/reaction` + `link/pathway`). Also attempt "
           "**fresh KEGG resolution of the 21 dark** via the ChEBI→KEGG bridge and KEGG "
           "name search.\n"
           "- **B. RDKit scaffold analogy (Tier-6)** — dark compounds are usually "
           "*substituted versions* of catalogued cores. Match each dark compound's Murcko "
           "scaffold against the 62 linked compounds to propose a pathway **by structural "
           "analogy**.\n"
           "- **C. PubMed literature mining** — compound-specific degradation/catabolism "
           "searches (NCBI E-utilities) to convert `T0_dark → T5_lit` where real evidence "
           "exists beyond the in-lakehouse PaperBLAST channel.\n\n"
           "enviPath was evaluated and dropped: its anonymous rules/prediction API returns "
           "HTML, not JSON, so it is unusable without authentication. All HTTP responses "
           "here are disk-cached for offline reruns."),

    ("code",
     "import pandas as pd, numpy as np\n"
     "import requests, json, time, re\n"
     "from pathlib import Path\n"
     "import matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt\n"
     "\n"
     "DATA = Path('../data'); FIG = Path('../figures')\n"
     "pd.set_option('display.max_columns', 40); pd.set_option('display.width', 200)\n"
     "\n"
     "res = pd.read_csv(DATA / 'resolved_compounds.tsv', sep='\\t')\n"
     "lk  = pd.read_csv(DATA / 'compound_linkage.tsv', sep='\\t')\n"
     "# carry SMILES + iupac onto the linkage frame\n"
     "lk = lk.merge(res[['compound_id','smiles','iupac_name']], on='compound_id', how='left')\n"
     "dark = lk[lk['best_tier'] == 'T0_dark'].copy()\n"
     "print('compounds:', len(lk), '| dark:', len(dark), '| KEGG-bearing:', int(lk['has_kegg'].sum()))\n"
     "print('dark all have SMILES:', dark['smiles'].notna().all())"),

    ("md", "## Cached HTTP helper (KEGG + NCBI E-utilities)"),

    ("code",
     "CACHE_PATH = DATA / 'deepen_cache.json'\n"
     "_cache = json.loads(CACHE_PATH.read_text()) if CACHE_PATH.exists() else {}\n"
     "_sess = requests.Session()\n"
     "\n"
     "def _get(url, params=None, kind='text'):\n"
     "    key = url + ('?' + '&'.join(f'{k}={v}' for k,v in sorted(params.items())) if params else '')\n"
     "    if key in _cache:\n"
     "        return _cache[key]\n"
     "    time.sleep(0.34)  # polite: KEGG <3 req/s, NCBI <3 req/s anonymous\n"
     "    try:\n"
     "        r = _sess.get(url, params=params, timeout=30)\n"
     "        body = r.json() if (kind=='json' and r.status_code==200) else r.text\n"
     "        out = {'status': r.status_code, 'body': body}\n"
     "    except Exception as e:\n"
     "        out = {'status': -1, 'body': None, 'error': str(e)}\n"
     "    _cache[key] = out\n"
     "    return out\n"
     "\n"
     "def _save():\n"
     "    CACHE_PATH.write_text(json.dumps(_cache))\n"
     "\n"
     "KEGG = 'https://rest.kegg.jp'\n"
     "EUTILS = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils'\n"
     "print('cache entries:', len(_cache))"),

    ("md", "## Build KEGG degradation-map dictionary (one bulk call)\n"
           "`list/pathway` gives every `mapNNNNN → name`; we flag any pathway whose name "
           "contains *degradation* / *catabolism* as catabolic. This is the key upgrade: "
           "membership in e.g. **map00903 Limonene and pinene degradation** (terpenoids), "
           "**map00071 Fatty acid degradation**, **map01220 Degradation of aromatic "
           "compounds** is direct evidence of a known catabolic route."),

    ("code",
     "r = _get(f'{KEGG}/list/pathway')\n"
     "MAP_NAME = {}\n"
     "for line in r['body'].strip().splitlines():\n"
     "    pid, _, nm = line.partition('\\t')\n"
     "    MAP_NAME[pid.replace('path:','').replace('map','')] = nm\n"
     "DEGRAD = {mid: nm for mid, nm in MAP_NAME.items()\n"
     "          if re.search(r'degrad|catabol', nm, re.I)}\n"
     "_save()\n"
     "print('total KEGG maps:', len(MAP_NAME), '| degradation maps:', len(DEGRAD))\n"
     "print('e.g.:', {k: DEGRAD[k] for k in list(DEGRAD)[:6]})"),

    ("md", "## Channel A — KEGG reaction + degradation-pathway membership (54 KEGG-bearing)"),

    ("code",
     "def kegg_reactions(cnum):\n"
     "    r = _get(f'{KEGG}/link/reaction/{cnum}')\n"
     "    if r['status'] != 200 or not r['body'].strip():\n"
     "        return []\n"
     "    return sorted({ln.split('\\t')[1].replace('rn:','')\n"
     "                   for ln in r['body'].strip().splitlines() if '\\t' in ln})\n"
     "\n"
     "def kegg_pathways(cnum):\n"
     "    r = _get(f'{KEGG}/link/pathway/{cnum}')\n"
     "    if r['status'] != 200 or not r['body'].strip():\n"
     "        return []\n"
     "    out = []\n"
     "    for ln in r['body'].strip().splitlines():\n"
     "        if '\\t' in ln:\n"
     "            out.append(ln.split('\\t')[1].replace('path:','').replace('map',''))\n"
     "    return sorted(set(out))\n"
     "\n"
     "rowsA = []\n"
     "for _, row in lk[lk['has_kegg']].iterrows():\n"
     "    c = str(row['kegg_id'])\n"
     "    rxns = kegg_reactions(c)\n"
     "    pws  = kegg_pathways(c)\n"
     "    deg  = [p for p in pws if p in DEGRAD]\n"
     "    rowsA.append(dict(compound_id=row['compound_id'], kegg_id=c,\n"
     "                      kegg_n_rxn=len(rxns), kegg_n_pw=len(pws),\n"
     "                      kegg_n_degpw=len(deg),\n"
     "                      kegg_deg_maps=';'.join(f'{d}:{DEGRAD[d]}' for d in deg)))\n"
     "_save()\n"
     "A = pd.DataFrame(rowsA)\n"
     "print('KEGG-bearing with >=1 real reaction:', int((A['kegg_n_rxn']>0).sum()), '/', len(A))\n"
     "print('KEGG-bearing in >=1 DEGRADATION pathway:', int((A['kegg_n_degpw']>0).sum()))\n"
     "print()\n"
     "show = A[A['kegg_n_degpw']>0].merge(lk[['compound_id','name','npc_pathway']], on='compound_id')\n"
     "print(show[['name','npc_pathway','kegg_n_rxn','kegg_deg_maps']].to_string(index=False))"),

    ("md", "## Channel A2 — fresh KEGG resolution of the 21 dark (ChEBI bridge + name search)"),

    ("code",
     "def chebi_to_kegg(chebi):\n"
     "    cid = str(chebi).split(':')[-1]\n"
     "    r = _get(f'{KEGG}/conv/compound/chebi:{cid}')\n"
     "    if r['status']==200 and r['body'].strip():\n"
     "        for ln in r['body'].strip().splitlines():\n"
     "            if '\\t' in ln:\n"
     "                return ln.split('\\t')[1].replace('cpd:','')\n"
     "    return None\n"
     "\n"
     "def kegg_find(name):\n"
     "    from urllib.parse import quote\n"
     "    nm = str(name).strip()\n"
     "    if len(nm) < 4:\n"
     "        return None\n"
     "    r = _get(f'{KEGG}/find/compound/{quote(nm)}')\n"
     "    if r['status']==200 and r['body'].strip():\n"
     "        first = r['body'].strip().splitlines()[0]\n"
     "        return first.split('\\t')[0].replace('cpd:','')\n"
     "    return None\n"
     "\n"
     "rowsA2 = []\n"
     "for _, row in dark.iterrows():\n"
     "    knum = via = None\n"
     "    if pd.notna(row.get('chebi_id')):\n"
     "        knum = chebi_to_kegg(row['chebi_id'])\n"
     "        if knum: via = 'chebi_bridge'\n"
     "    if not knum:\n"
     "        for nm in [row['name'], row.get('iupac_name')]:\n"
     "            if pd.notna(nm):\n"
     "                knum = kegg_find(nm)\n"
     "                if knum:\n"
     "                    via = 'name_search'; break\n"
     "    ndeg = nrxn = 0; degmaps = ''\n"
     "    if knum:\n"
     "        rxns = kegg_reactions(knum); pws = kegg_pathways(knum)\n"
     "        deg = [p for p in pws if p in DEGRAD]\n"
     "        nrxn, ndeg = len(rxns), len(deg)\n"
     "        degmaps = ';'.join(f'{d}:{DEGRAD[d]}' for d in deg)\n"
     "    rowsA2.append(dict(compound_id=row['compound_id'], name=row['name'],\n"
     "                       new_kegg=knum, kegg_via=via, kegg_n_rxn=nrxn,\n"
     "                       kegg_n_degpw=ndeg, kegg_deg_maps=degmaps))\n"
     "_save()\n"
     "A2 = pd.DataFrame(rowsA2)\n"
     "print('dark compounds newly mapped to a KEGG compound:', int(A2['new_kegg'].notna().sum()), '/', len(A2))\n"
     "print(A2[A2['new_kegg'].notna()][['name','new_kegg','kegg_via','kegg_n_rxn','kegg_n_degpw']].to_string(index=False))"),

    ("md", "## Channel B — RDKit scaffold analogy (Tier-6 *overlay*, not hard linkage)\n"
           "**Rigor note:** a first pass using `MakeScaffoldGeneric` (which abstracts every "
           "atom to carbon and every bond to single) produced chemically *false* analogies "
           "— a saturated cyclohexylamine matched an aromatic phthalate ester, and "
           "N-heterocyclic quinolinones matched O-heterocyclic coumarins — because "
           "heteroatoms and aromaticity were erased. We therefore use the **real Bemis-"
           "Murcko scaffold (heteroatoms + aromaticity preserved)** and additionally gate "
           "every candidate on **Morgan-fingerprint Tanimoto ≥ 0.40** to the analog. A "
           "match must share the *same real ring system* AND be quantitatively similar.\n\n"
           "Crucially, scaffold analogy is treated as a **candidate-by-analogy overlay for "
           "wet-lab prioritisation — it does NOT count toward hard pathway linkage.** A "
           "dark compound stays dark unless it gains *measured*, *KEGG-reaction*, or "
           "*screened-literature* support; the analogy only annotates it with a structural "
           "hypothesis."),

    ("code",
     "from rdkit import Chem\n"
     "from rdkit.Chem.Scaffolds import MurckoScaffold\n"
     "from rdkit.Chem import rdMolDescriptors, DataStructs\n"
     "from rdkit import RDLogger; RDLogger.DisableLog('rdApp.*')\n"
     "\n"
     "def mol(s):\n"
     "    return Chem.MolFromSmiles(s) if isinstance(s, str) and s else None\n"
     "def real_scaffold(m):\n"
     "    '''Bemis-Murcko scaffold WITH heteroatoms + aromaticity preserved.'''\n"
     "    if m is None: return None\n"
     "    try:\n"
     "        core = MurckoScaffold.GetScaffoldForMol(m)\n"
     "        if core is None or core.GetNumAtoms()==0: return None\n"
     "        return Chem.MolToSmiles(core)\n"
     "    except Exception:\n"
     "        return None\n"
     "def fp(m):\n"
     "    return rdMolDescriptors.GetMorganFingerprintAsBitVect(m, 2, 2048) if m is not None else None\n"
     "\n"
     "lk['mol'] = lk['smiles'].map(mol)\n"
     "lk['rscaf'] = lk['mol'].map(real_scaffold)\n"
     "lk['fp'] = lk['mol'].map(fp)\n"
     "linked = lk[lk['best_tier'] != 'T0_dark'].copy()\n"
     "TANI_MIN = 0.40\n"
     "\n"
     "rowsB = []\n"
     "for _, d in lk[lk['best_tier']=='T0_dark'].iterrows():\n"
     "    dm, dscaf, dfp = d['mol'], d['rscaf'], d['fp']\n"
     "    best = dict(analog=None, kind=None, tier='', pw='', tani=0.0)\n"
     "    if dscaf is not None and dfp is not None:\n"
     "        # candidates that share the identical real scaffold\n"
     "        same = linked[linked['rscaf'] == dscaf]\n"
     "        for _, a in same.iterrows():\n"
     "            if a['fp'] is None: continue\n"
     "            t = DataStructs.TanimotoSimilarity(dfp, a['fp'])\n"
     "            if t >= TANI_MIN and t > best['tani']:\n"
     "                best = dict(analog=a['name'], kind='same_real_scaffold',\n"
     "                            tier=a['best_tier'], pw=a['npc_pathway'], tani=round(t,3))\n"
     "    rowsB.append(dict(compound_id=d['compound_id'], name=d['name'],\n"
     "                      npc_pathway=d['npc_pathway'], analog=best['analog'],\n"
     "                      analog_kind=best['kind'], analog_tier=best['tier'],\n"
     "                      analog_pathway=best['pw'], analog_tani=best['tani']))\n"
     "B = pd.DataFrame(rowsB)\n"
     "print(f'dark with chemically-meaningful analog (same real scaffold & Tanimoto>={TANI_MIN}):',\n"
     "      int(B['analog'].notna().sum()), '/', len(B))\n"
     "print(B[B['analog'].notna()][['name','analog','analog_tani','analog_tier','analog_pathway']].to_string(index=False))"),

    ("md", "## Channel C — compound-specific PubMed degradation literature (21 dark)\n"
           "For each dark compound we query PubMed for degradation/catabolism evidence and "
           "keep the hit count + top PMIDs/titles. A light title screen (mentions of "
           "degrad/catabol/biotransform/metaboli + a microbial token) marks *screened* "
           "hits to avoid over-crediting incidental matches. This is compound-specific "
           "evidence (Tier-5), distinct from the scaffold analogy in Channel B."),

    ("code",
     "DEG_WORDS = re.compile(r'degrad|catabol|biotransform|metaboli|biodegrad', re.I)\n"
     "MICROBE   = re.compile(r'bacter|microb|pseudomonas|rhodococcus|soil|strain|isolat', re.I)\n"
     "\n"
     "def esearch(term, retmax=5):\n"
     "    r = _get(f'{EUTILS}/esearch.fcgi',\n"
     "             params={'db':'pubmed','term':term,'retmode':'json','retmax':retmax}, kind='json')\n"
     "    if r['status']==200 and isinstance(r['body'], dict):\n"
     "        es = r['body'].get('esearchresult', {})\n"
     "        return int(es.get('count', 0)), es.get('idlist', [])\n"
     "    return 0, []\n"
     "\n"
     "def esummary_titles(pmids):\n"
     "    if not pmids: return []\n"
     "    r = _get(f'{EUTILS}/esummary.fcgi',\n"
     "             params={'db':'pubmed','id':','.join(pmids),'retmode':'json'}, kind='json')\n"
     "    if r['status']==200 and isinstance(r['body'], dict):\n"
     "        res = r['body'].get('result', {})\n"
     "        return [res[u].get('title','') for u in res.get('uids', [])]\n"
     "    return []\n"
     "\n"
     "def query_terms(name, iupac):\n"
     "    cands = []\n"
     "    for nm in [name, iupac]:\n"
     "        if isinstance(nm, str) and nm.strip() and not nm.startswith('Cc1_'):\n"
     "            c = re.sub(r'[_]+',' ', nm).strip()\n"
     "            if c not in cands: cands.append(c)\n"
     "    return cands\n"
     "\n"
     "rowsC = []\n"
     "for _, d in dark.iterrows():\n"
     "    best = dict(n=0, pmids=[], titles=[], term='')\n"
     "    for core in query_terms(d['name'], d.get('iupac_name')):\n"
     "        term = f'(\"{core}\") AND (degradation OR catabolism OR biodegradation OR metabolism)'\n"
     "        n, ids = esearch(term)\n"
     "        if n > best['n']:\n"
     "            best = dict(n=n, pmids=ids, titles=esummary_titles(ids), term=core)\n"
     "    screened = [t for t in best['titles'] if DEG_WORDS.search(t) and MICROBE.search(t)]\n"
     "    rowsC.append(dict(compound_id=d['compound_id'], name=d['name'],\n"
     "                      lit_n=best['n'], lit_screened=len(screened),\n"
     "                      lit_term=best['term'], lit_top_pmids=';'.join(best['pmids'][:3]),\n"
     "                      lit_top_title=(best['titles'][0] if best['titles'] else '')))\n"
     "_save()\n"
     "C = pd.DataFrame(rowsC)\n"
     "print('dark with >=1 PubMed hit:', int((C['lit_n']>0).sum()), '/', len(C))\n"
     "print('dark with screened (degradation+microbial) title:', int((C['lit_screened']>0).sum()))\n"
     "print()\n"
     "print(C[C['lit_n']>0][['name','lit_n','lit_screened','lit_top_title']].to_string(index=False))"),

    ("md", "## Integrate — hard linkage vs analogy overlay; dark set preserved\n"
           "Re-rank every compound. The **hard tier ladder** counts only evidence that a "
           "microbe could *transform* the molecule:\n"
           "- **T1_measured** — RB-TnSeq carbon-source fitness.\n"
           "- **T2_kegg_degrad** — member of a KEGG *degradation* pathway (strongest in-DB catabolic signal).\n"
           "- **T2_3_reaction** — ≥1 ModelSEED reaction (NB02 channel).\n"
           "- **T2_3_kegg_rxn** — ≥1 real KEGG reaction (upgrade from bare `has_kegg`).\n"
           "- **T3_kegg** — KEGG id only, no reaction surfaced.\n"
           "- **T5_lit_strong** — in-lakehouse PaperBLAST curated hit (NB02 channel).\n"
           "- **T5_lit_dark** — compound-specific PubMed degradation evidence (screened title).\n\n"
           "**T6_analogy is an overlay, not a hard tier.** `hard_linked` (the coverage "
           "headline) excludes it. A `was_dark` compound is only **rescued** if it gains a "
           "*hard* tier; the scaffold analogy merely annotates remaining dark compounds "
           "with a structural hypothesis (`has_analogy`) for wet-lab triage. This keeps the "
           "21-compound knowledge gap honest."),

    ("code",
     "aug = lk.drop(columns=['mol','rscaf','fp']).copy()\n"
     "aug['was_dark'] = aug['best_tier'] == 'T0_dark'\n"
     "\n"
     "# fold KEGG reaction/degradation info (Channel A for KEGG-bearing)\n"
     "aug = aug.merge(A[['compound_id','kegg_n_rxn','kegg_n_degpw','kegg_deg_maps']],\n"
     "                on='compound_id', how='left')\n"
     "# fold Channel A2 (dark newly resolved) — combine counts\n"
     "a2 = A2.rename(columns={'kegg_n_rxn':'kegg_n_rxn2','kegg_n_degpw':'kegg_n_degpw2',\n"
     "                        'kegg_deg_maps':'kegg_deg_maps2'})\n"
     "aug = aug.merge(a2[['compound_id','new_kegg','kegg_via','kegg_n_rxn2','kegg_n_degpw2','kegg_deg_maps2']],\n"
     "                on='compound_id', how='left')\n"
     "for col in ['kegg_n_rxn','kegg_n_degpw','kegg_n_rxn2','kegg_n_degpw2']:\n"
     "    aug[col] = aug[col].fillna(0).astype(int)\n"
     "aug['kegg_n_rxn']   = aug[['kegg_n_rxn','kegg_n_rxn2']].max(axis=1)\n"
     "aug['kegg_n_degpw'] = aug[['kegg_n_degpw','kegg_n_degpw2']].max(axis=1)\n"
     "aug['kegg_deg_maps'] = aug['kegg_deg_maps'].fillna('').where(\n"
     "    aug['kegg_deg_maps'].fillna('')!='' , aug['kegg_deg_maps2'].fillna(''))\n"
     "# fold Channel B (analogy overlay) and C (literature)\n"
     "aug = aug.merge(B[['compound_id','analog','analog_kind','analog_tier','analog_pathway','analog_tani']],\n"
     "                on='compound_id', how='left')\n"
     "aug = aug.merge(C[['compound_id','lit_n','lit_screened','lit_top_pmids','lit_top_title']],\n"
     "                on='compound_id', how='left')\n"
     "aug['lit_n'] = aug['lit_n'].fillna(0).astype(int)\n"
     "aug['lit_screened'] = aug['lit_screened'].fillna(0).astype(int)\n"
     "\n"
     "def hard_tier(r):\n"
     "    if r['best_tier'] == 'T1_measured':      return 'T1_measured'\n"
     "    if r['kegg_n_degpw'] > 0:                 return 'T2_kegg_degrad'\n"
     "    if r['best_tier'] == 'T2_3_reaction':     return 'T2_3_reaction'\n"
     "    if r['kegg_n_rxn'] > 0:                    return 'T2_3_kegg_rxn'\n"
     "    if r['best_tier'] == 'T3_kegg':           return 'T3_kegg'\n"
     "    if str(r['best_tier']).startswith('T5_lit'): return r['best_tier']\n"
     "    if r.get('lit_screened',0) > 0:           return 'T5_lit_dark'\n"
     "    if r['best_tier'] == 'T5_lit_lowprec':    return 'T5_lit_lowprec'\n"
     "    return 'T0_dark'\n"
     "\n"
     "aug['deep_tier'] = aug.apply(hard_tier, axis=1)\n"
     "aug['hard_linked'] = aug['deep_tier'] != 'T0_dark'\n"
     "aug['has_analogy'] = aug['analog'].notna()\n"
     "aug['rescued'] = aug['was_dark'] & aug['hard_linked']\n"
     "aug['analogy_only'] = aug['was_dark'] & ~aug['hard_linked'] & aug['has_analogy']\n"
     "aug['deep_dark'] = aug['was_dark'] & ~aug['hard_linked'] & ~aug['has_analogy']\n"
     "print('NB02 dark:', int(aug['was_dark'].sum()))\n"
     "print('  hard-rescued (gained measured/KEGG-rxn/lit):', int(aug['rescued'].sum()))\n"
     "print('  analogy-only (structural hypothesis, still not hard-linked):', int(aug['analogy_only'].sum()))\n"
     "print('  deep dark (no evidence at all):', int(aug['deep_dark'].sum()))"),

    ("code",
     "# hard tier distribution before vs after\n"
     "order = ['T1_measured','T2_kegg_degrad','T2_3_reaction','T2_3_kegg_rxn','T3_kegg',\n"
     "         'T5_lit_strong','T5_lit','T5_lit_dark','T5_lit_lowprec','T0_dark']\n"
     "before = lk['best_tier'].value_counts()\n"
     "after  = aug['deep_tier'].value_counts()\n"
     "comp = pd.DataFrame({'NB02': before, 'NB02b': after}).reindex(order).fillna(0).astype(int)\n"
     "print(comp.to_string())\n"
     "print()\n"
     "hl_before = int((lk['best_tier']!='T0_dark').sum())\n"
     "hl_after  = int(aug['hard_linked'].sum())\n"
     "print(f'HARD LINKAGE: {hl_before}/83 ({hl_before/83:.0%}) -> {hl_after}/83 ({hl_after/83:.0%})')\n"
     "print(f'  qualitative upgrade: {int((aug[\"deep_tier\"]==\"T2_kegg_degrad\").sum())} compounds now in a confirmed KEGG DEGRADATION pathway')\n"
     "print(f'ANALOGY OVERLAY: {int(aug[\"has_analogy\"].sum())} dark compounds carry a structural hypothesis (NOT counted as linked)')"),

    ("code",
     "# detail: degradation-pathway compounds, analogy overlay, and deep dark\n"
     "print('=== CONFIRMED KEGG DEGRADATION PATHWAY (T2_kegg_degrad) ===')\n"
     "print(aug[aug['deep_tier']=='T2_kegg_degrad'][['name','npc_pathway','kegg_n_rxn','kegg_deg_maps']].to_string(index=False))\n"
     "print()\n"
     "print('=== ANALOGY OVERLAY (still dark, structural hypothesis only) ===')\n"
     "ao = aug[aug['analogy_only']][['name','npc_pathway','analog','analog_tani','analog_tier','analog_pathway']]\n"
     "print(ao.to_string(index=False))\n"
     "print()\n"
     "print('=== DEEP DARK (no evidence, no analog) ===')\n"
     "print(aug[aug['deep_dark']][['compound_id','name','npc_pathway']].to_string(index=False))"),

    ("md", "## Coverage by class (hard linkage) + figure"),

    ("code",
     "byc = aug.groupby('npc_pathway').agg(n=('compound_id','size'),\n"
     "        hard_before=('was_dark', lambda s: int((~s).sum())),\n"
     "        hard_after=('hard_linked','sum'),\n"
     "        analogy=('analogy_only','sum')).sort_values('n', ascending=False)\n"
     "byc['deep_dark'] = byc['n'] - byc['hard_after'] - byc['analogy']\n"
     "print(byc.to_string())"),

    ("code",
     "fig, axes = plt.subplots(1, 2, figsize=(13, 4.6))\n"
     "# left: per-class stacked hard / analogy / deep-dark\n"
     "x = np.arange(len(byc))\n"
     "axes[0].barh(x, byc['hard_after'], color='#2c7fb8', label='hard-linked')\n"
     "axes[0].barh(x, byc['analogy'], left=byc['hard_after'], color='#9e9ac8', label='analogy overlay')\n"
     "axes[0].barh(x, byc['deep_dark'], left=byc['hard_after']+byc['analogy'], color='#d7301f', label='deep dark')\n"
     "axes[0].set_yticks(x); axes[0].set_yticklabels(byc.index, fontsize=8)\n"
     "axes[0].invert_yaxis(); axes[0].set_xlabel('compounds'); axes[0].legend(fontsize=8)\n"
     "axes[0].set_title('Per-class: hard linkage + analogy overlay + deep dark')\n"
     "# right: hard tier distribution\n"
     "tc = aug['deep_tier'].value_counts().reindex(order).dropna()\n"
     "colors = {'T1_measured':'#08519c','T2_kegg_degrad':'#238b45','T2_3_reaction':'#41ab5d',\n"
     "          'T2_3_kegg_rxn':'#74c476','T3_kegg':'#a1d99b','T5_lit_strong':'#fe9929',\n"
     "          'T5_lit':'#fdae6b','T5_lit_dark':'#fec44f','T5_lit_lowprec':'#fee391','T0_dark':'#d7301f'}\n"
     "axes[1].barh(range(len(tc)), tc.values, color=[colors.get(t,'#888') for t in tc.index])\n"
     "axes[1].set_yticks(range(len(tc))); axes[1].set_yticklabels(tc.index, fontsize=8)\n"
     "axes[1].invert_yaxis(); axes[1].set_xlabel('compounds')\n"
     "axes[1].set_title('Hard confidence tiers (n=83)')\n"
     "for i,v in enumerate(tc.values): axes[1].text(v+0.3, i, str(int(v)), va='center', fontsize=8)\n"
     "fig.tight_layout(); fig.savefig(FIG / '02b_linkage_deepened.png', dpi=150)\n"
     "print('saved 02b_linkage_deepened.png'); plt.close(fig)"),

    ("md", "## Save deepened linkage table"),

    ("code",
     "out_cols = ['compound_id','name','npc_pathway','inchikey','kegg_id','chebi_id',\n"
     "            'best_tier','was_dark','deep_tier','rescued',\n"
     "            'kegg_n_rxn','kegg_n_degpw','kegg_deg_maps','new_kegg','kegg_via',\n"
     "            'analog','analog_kind','analog_tier','analog_pathway',\n"
     "            'lit_n','lit_screened','lit_top_pmids','lit_top_title',\n"
     "            'fb_carbon','msd_match','msd_n_rxn','has_kegg','lit_strong']\n"
     "out_cols = [c for c in out_cols if c in aug.columns]\n"
     "aug[out_cols].to_csv(DATA / 'compound_linkage_deepened.tsv', sep='\\t', index=False)\n"
     "print('wrote data/compound_linkage_deepened.tsv', aug[out_cols].shape)\n"
     "aug[out_cols].head(8)"),
]

build_and_run("02b_linkage_deepening.ipynb", cells)
