from _build import build_and_run

cells = [
    ("md", "# NB09 — Deepening the census: bioavailability, chassis, clade conservation, dark-matter taxonomy\n\n"
           "NB01–NB08 built the tiered knowledge product and the honest gap map. This notebook adds "
           "four content layers the user audit flagged as missing — each chosen to *characterize the "
           "gap*, not to inflate coverage. **Pervasive honesty flags carried throughout:**\n\n"
           "- **n = 9 callable vs 74 dark** underpowers every callable-vs-dark contrast. All such "
           "comparisons here are **descriptive / directional only** — medians and a Mann–Whitney U "
           "are reported as effect-direction indicators, not as hypothesis tests we are powered for.\n"
           "- **Catabolic direction is a reversible-reaction heuristic** (NB03), not proof of "
           "metabolic flux. 'Utilizer' means *carries the genetic signature of a catabolic-direction "
           "route*, not *measured to grow*.\n"
           "- **Confidence tiers are not comparable across compounds** — a T2 reaction call and a T1 "
           "measured call are different kinds of evidence.\n\n"
           "The four parts:\n"
           "1. **Physicochemistry / bioavailability** — PubChem computed properties for all 83; "
           "callable-vs-dark and groundwater-vs-necromass contrasts. Bioavailability is framed as a "
           "*ceiling* on the environmental atlas: a compound that is poorly soluble or non-"
           "transportable cannot be widely bioavailable however many genomes encode a route.\n"
           "2. **Utilizer → compound transpose** — the chassis view: which genomes are generalists "
           "vs specialists, and a provenance audit (all callable evidence is catabolic-direction).\n"
           "3. **Per-clade conservation** — is a capacity fixed within a genus or scattered?\n"
           "4. **Dark-matter taxonomy** — partition the 74 dark compounds into "
           "*biosynthesis-known-but-catabolism-unknown* vs *fully orphan*, flag MIBiG as the external "
           "resource to consult, and stratify the dark fraction by source."),

    ("code",
     "import os, json, time\n"
     "import pandas as pd, numpy as np, requests\n"
     "import matplotlib\n"
     "matplotlib.use('Agg')\n"
     "import matplotlib.pyplot as plt\n"
     "from scipy.stats import mannwhitneyu\n"
     "from pathlib import Path\n"
     "DATA = Path('../data'); FIG = Path('../figures')\n"
     "pd.set_option('display.max_columns', 50); pd.set_option('display.width', 240)\n"
     "\n"
     "master = pd.read_csv(DATA / 'census_master_summary.tsv', sep='\\t')\n"
     "res = pd.read_csv(DATA / 'resolved_compounds.tsv', sep='\\t')\n"
     "print('master compounds:', len(master), '| callable:', int(master['callable'].sum()),\n"
     "      '| by source:', dict(master['source_short'].value_counts()))"),

    # ---- PART 1: physicochemistry / bioavailability ----
    ("md", "## Part 1 — Physicochemistry & bioavailability\n"
           "PubChem PUG-REST computed properties for all 83 CIDs (cached to "
           "`data/pubchem_properties_cache.json`, so re-execution is offline). Properties chosen for "
           "their bearing on **bioavailability** — the physical ceiling on how much an environmental "
           "community can access a compound, independent of whether any genome encodes a route:\n"
           "- **XLogP** — lipophilicity; very high or very low impairs aqueous availability / "
           "membrane transport.\n"
           "- **TPSA** — topological polar surface area; high TPSA ⇒ poor passive permeability.\n"
           "- **MolecularWeight / HeavyAtomCount** — size; large molecules need active uptake.\n"
           "- **HBondDonorCount / HBondAcceptorCount** — H-bonding burden (Lipinski-style).\n"
           "- **Complexity** — structural elaboration; secondary metabolites score high."),

    ("code",
     "PROPS = ['MolecularWeight','XLogP','TPSA','HBondDonorCount','HBondAcceptorCount',\n"
     "         'RotatableBondCount','Complexity','HeavyAtomCount','Charge']\n"
     "cache_path = DATA / 'pubchem_properties_cache.json'\n"
     "cache = json.loads(cache_path.read_text()) if cache_path.exists() else {}\n"
     "cids = [int(c) for c in res['cid'].dropna().unique().tolist()]\n"
     "todo = [c for c in cids if str(c) not in cache]\n"
     "def fetch_batch(batch):\n"
     "    url = ('https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/'\n"
     "           + ','.join(map(str, batch)) + '/property/' + ','.join(PROPS) + '/JSON')\n"
     "    r = requests.get(url, timeout=30)\n"
     "    if r.status_code != 200: return\n"
     "    for rec in r.json()['PropertyTable']['Properties']:\n"
     "        cache[str(rec['CID'])] = {p: rec.get(p) for p in PROPS}\n"
     "for i in range(0, len(todo), 50):\n"
     "    fetch_batch(todo[i:i+50]); time.sleep(0.25)\n"
     "cache_path.write_text(json.dumps(cache))\n"
     "props = pd.DataFrame([{'cid': int(k), **v} for k, v in cache.items()])\n"
     "for p in PROPS: props[p] = pd.to_numeric(props[p], errors='coerce')\n"
     "print('properties cached for %d/%d CIDs' % (props['cid'].notna().sum(), len(cids)))\n"
     "pc = res[['compound_id','cid']].dropna().copy(); pc['cid'] = pc['cid'].astype(int)\n"
     "phys = master.merge(pc, on='compound_id', how='left').merge(props, on='cid', how='left')\n"
     "phys.to_csv(DATA / 'compound_physicochem.tsv', sep='\\t', index=False)\n"
     "print('wrote data/compound_physicochem.tsv', phys.shape)"),

    ("code",
     "def contrast(df, group_col, a_label, b_label, props=PROPS):\n"
     "    A = df[df[group_col] == a_label]; B = df[df[group_col] == b_label]\n"
     "    rows = []\n"
     "    for p in props:\n"
     "        xa = A[p].dropna(); xb = B[p].dropna()\n"
     "        if len(xa) < 2 or len(xb) < 2: continue\n"
     "        try: _, pv = mannwhitneyu(xa, xb, alternative='two-sided')\n"
     "        except ValueError: pv = np.nan\n"
     "        rows.append(dict(prop=p, med_a=xa.median(), med_b=xb.median(),\n"
     "                         dir=('a>b' if xa.median() > xb.median() else 'a<b'), p_dir=pv))\n"
     "    return pd.DataFrame(rows)\n"
     "\n"
     "phys['call_lbl'] = np.where(phys['callable'], 'callable', 'dark')\n"
     "cvd = contrast(phys, 'call_lbl', 'callable', 'dark')\n"
     "print('=== callable (n=%d) vs dark (n=%d) — DIRECTIONAL ONLY, underpowered ===' %\n"
     "      (int(phys['callable'].sum()), int((~phys['callable']).sum())))\n"
     "print(cvd.to_string(index=False, formatters={'med_a':'{:.1f}'.format,'med_b':'{:.1f}'.format,\n"
     "      'p_dir':'{:.3f}'.format}))\n"
     "gvn = contrast(phys, 'source_short', 'groundwater', 'necromass')\n"
     "print('\\n=== groundwater (n=59) vs necromass (n=24) ===')\n"
     "print(gvn.to_string(index=False, formatters={'med_a':'{:.1f}'.format,'med_b':'{:.1f}'.format,\n"
     "      'p_dir':'{:.3f}'.format}))"),

    ("code",
     "fig, axes = plt.subplots(2, 3, figsize=(13, 7.5))\n"
     "panel = ['MolecularWeight','XLogP','TPSA','HBondDonorCount','Complexity','RotatableBondCount']\n"
     "for ax, p in zip(axes.ravel(), panel):\n"
     "    groups = [phys[phys['call_lbl']==g][p].dropna() for g in ['callable','dark']]\n"
     "    ax.boxplot(groups, labels=['callable\\n(n=%d)'%len(groups[0]),'dark\\n(n=%d)'%len(groups[1])],\n"
     "               widths=0.6, showfliers=False)\n"
     "    for i, gv in enumerate(groups, 1):\n"
     "        ax.scatter(np.random.normal(i, 0.05, len(gv)), gv, s=12, alpha=0.5,\n"
     "                   color=['#2b8cbe','#b30000'][i-1])\n"
     "    ax.set_title(p, fontsize=10)\n"
     "fig.suptitle('Physicochemistry: callable vs organism-dark (descriptive; n=9 vs 74)', fontsize=12)\n"
     "fig.tight_layout(); fig.savefig(FIG / '09a_physicochem_callable_dark.png', dpi=150)\n"
     "print('saved 09a_physicochem_callable_dark.png'); plt.close(fig)"),

    ("code",
     "# bioavailability ceiling: logP vs TPSA scatter, sized by MW, coloured by source, marked callable\n"
     "fig, ax = plt.subplots(figsize=(9, 6.5))\n"
     "for src, col in [('groundwater','#1f78b4'), ('necromass','#33a02c')]:\n"
     "    s = phys[phys['source_short']==src]\n"
     "    ax.scatter(s['XLogP'], s['TPSA'], s=np.clip(s['MolecularWeight']/2, 10, 300),\n"
     "               alpha=0.55, color=col, edgecolor='k', linewidth=0.3, label=src)\n"
     "cal = phys[phys['callable']]\n"
     "ax.scatter(cal['XLogP'], cal['TPSA'], s=60, facecolors='none', edgecolors='red',\n"
     "           linewidths=1.6, label='callable')\n"
     "ax.axvspan(-100, 0, color='grey', alpha=0.08); ax.axvspan(5, 100, color='grey', alpha=0.08)\n"
     "ax.axhline(140, color='grey', ls='--', lw=0.8)\n"
     "ax.set_xlim(phys['XLogP'].min()-1, phys['XLogP'].max()+1)\n"
     "ax.set_ylim(-5, max(160, phys['TPSA'].max()+10))\n"
     "ax.set_xlabel('XLogP (lipophilicity)'); ax.set_ylabel('TPSA (polar surface area, A^2)')\n"
     "ax.set_title('Bioavailability space (marker size = MW). Shaded/dashed = transport-unfavourable')\n"
     "ax.legend(loc='upper right', fontsize=9)\n"
     "fig.tight_layout(); fig.savefig(FIG / '09a_bioavailability_space.png', dpi=150)\n"
     "print('saved 09a_bioavailability_space.png'); plt.close(fig)"),

    ("md", "**Bioavailability as a ceiling on the atlas.** The environmental atlas (NB07) can only "
           "register a compound that is physically available to the community. Compounds in the "
           "transport-unfavourable zones (very low/high XLogP, TPSA ≳ 140 Å²) sit under a "
           "bioavailability ceiling that no number of genome-encoded routes can lift — so a low "
           "field signal for such a compound is *expected*, not evidence of a missing capacity. This "
           "reframes part of the dark set: some dark compounds may be dark because they are rarely "
           "bioavailable, not because the genetics are unknown."),

    # ---- PART 2: utilizer -> compound transpose, chassis, provenance ----
    ("md", "## Part 2 — Utilizer→compound transpose: the chassis view\n"
           "NB04/06 are organized compound→organism. Transposing to organism→compound asks: among "
           "the 800 genomes with ≥1 catabolic call, which are **generalist chassis** (carry several "
           "of the 8 capacities) vs **specialists** (one)? And a **provenance audit**: every callable "
           "call is catabolic-direction by construction (NB03), so the chassis portfolios are "
           "degradation portfolios, not biosynthetic ones."),

    ("code",
     "pop = pd.read_csv(DATA / 'compound_organism_predictions.tsv', sep='\\t')\n"
     "vers = pop.groupby('genome_id')['compound_id'].nunique()\n"
     "dist = vers.value_counts().sort_index()\n"
     "print('chassis versatility (catabolic capacities per genome, of 8):')\n"
     "for k, v in dist.items(): print(f'  {k}: {v:4d} genomes')\n"
     "n_spec = int((vers == 1).sum()); n_gen = int((vers >= 3).sum())\n"
     "print(f'\\nspecialists (1 capacity): {n_spec}  |  generalists (>=3): {n_gen}')\n"
     "# generalist taxonomy\n"
     "tax = pop[['genome_id','taxon_name']].drop_duplicates('genome_id').set_index('genome_id')\n"
     "gen_ids = vers[vers >= 3].index\n"
     "gen_tax = tax.loc[gen_ids].copy()\n"
     "gen_tax['genus'] = gen_tax['taxon_name'].astype(str).str.split().str[0]\n"
     "print('\\ngeneralist chassis by genus:')\n"
     "print(gen_tax['genus'].value_counts().to_string())\n"
     "# provenance audit\n"
     "print('\\nprovenance of callable evidence (tier of each genome-compound call):')\n"
     "print(pop['tier'].value_counts().to_string())\n"
     "print('-> 100% catabolic-direction (NB03 filter); biosynthetic-only signatures were excluded')\n"
     "print('   and fall in the dark set (see Part 4 only_biosynthetic_signatures bucket).')"),

    ("code",
     "# per-compound chassis breadth: how many genomes / genera carry each capacity\n"
     "pop['genus'] = pop['taxon_name'].astype(str).str.split().str[0]\n"
     "cap = (pop.groupby('name')\n"
     "       .agg(n_genomes=('genome_id','nunique'), n_genera=('genus','nunique'))\n"
     "       .sort_values('n_genomes', ascending=False))\n"
     "print('capacity breadth across chassis:')\n"
     "print(cap.to_string())\n"
     "\n"
     "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))\n"
     "ax1.bar(dist.index, dist.values, color='#41b6c4', edgecolor='k', linewidth=0.4)\n"
     "ax1.set_xlabel('catabolic capacities per genome (of 8)'); ax1.set_ylabel('genomes')\n"
     "ax1.set_title('Chassis versatility (n=%d genomes)' % len(vers))\n"
     "ax1.set_yscale('log')\n"
     "cap_s = cap.sort_values('n_genomes')\n"
     "ax2.barh(cap_s.index, cap_s['n_genomes'], color='#fc8d59', edgecolor='k', linewidth=0.4)\n"
     "ax2.set_xlabel('genomes carrying capacity'); ax2.set_title('Per-compound chassis breadth')\n"
     "for i, (n_g, nm) in enumerate(zip(cap_s['n_genomes'], cap_s.index)):\n"
     "    ax2.text(n_g+3, i, str(int(n_g)), va='center', fontsize=8)\n"
     "fig.tight_layout(); fig.savefig(FIG / '09b_chassis.png', dpi=150)\n"
     "print('saved 09b_chassis.png'); plt.close(fig)"),

    # ---- PART 3: per-clade conservation ----
    ("md", "## Part 3 — Per-clade conservation of utilization\n"
           "Is a catabolic capacity **fixed within a clade** (most genomes of a genus carry it ⇒ "
           "vertically conserved / clade-defining) or **scattered** (a minority ⇒ horizontally "
           "mobile or strain-variable)? For each genus with enough genomes in the DB, compute the "
           "fraction carrying each capacity. **Caveat:** the denominator is genomes *in the ENIGMA "
           "depot that have any call*, not a clean clade census, so 'conservation' here is "
           "within-sampled-genus prevalence, read directionally."),

    ("code",
     "# denominator: all genomes per genus in the depot is not available offline; use the\n"
     "# phylo map which carries genus + n_genomes per (compound,taxon). Build genus x compound\n"
     "# prevalence from the predictions (carriers) over genus genome totals from the predictions.\n"
     "genus_tot = pop.groupby('genus')['genome_id'].nunique()\n"
     "big = genus_tot[genus_tot >= 5].index  # genera with >=5 sampled genomes\n"
     "carr = (pop[pop['genus'].isin(big)]\n"
     "        .groupby(['genus','name'])['genome_id'].nunique().unstack(fill_value=0))\n"
     "frac = carr.div(genus_tot.loc[carr.index], axis=0)\n"
     "frac = frac.loc[genus_tot.loc[frac.index].sort_values(ascending=False).index]\n"
     "print('genus x compound carrier fraction (genera with >=5 sampled genomes):')\n"
     "print((frac*100).round(0).astype(int).to_string())\n"
     "# conservation summary: per compound, max within-genus prevalence\n"
     "print('\\nper-compound peak within-genus conservation:')\n"
     "for c in frac.columns:\n"
     "    top = frac[c].sort_values(ascending=False).head(1)\n"
     "    print(f'  {c:24s} peak {top.iloc[0]*100:3.0f}% in {top.index[0]}')"),

    ("code",
     "fig, ax = plt.subplots(figsize=(10, max(4, 0.4*len(frac))))\n"
     "im = ax.imshow(frac.values, cmap='YlGnBu', vmin=0, vmax=1, aspect='auto')\n"
     "ax.set_xticks(range(len(frac.columns)))\n"
     "ax.set_xticklabels(frac.columns, rotation=45, ha='right', fontsize=8)\n"
     "ax.set_yticks(range(len(frac.index)))\n"
     "ax.set_yticklabels([f'{g} (n={genus_tot[g]})' for g in frac.index], fontsize=8)\n"
     "for i in range(len(frac.index)):\n"
     "    for j in range(len(frac.columns)):\n"
     "        v = frac.values[i, j]\n"
     "        if v > 0: ax.text(j, i, f'{v*100:.0f}', ha='center', va='center', fontsize=6,\n"
     "                          color='white' if v > 0.5 else 'black')\n"
     "ax.set_title('Within-genus carrier fraction (%) — clade conservation of catabolic capacity')\n"
     "fig.colorbar(im, ax=ax, shrink=0.6, label='fraction of genus genomes')\n"
     "fig.tight_layout(); fig.savefig(FIG / '09c_clade_conservation.png', dpi=150)\n"
     "print('saved 09c_clade_conservation.png'); plt.close(fig)"),

    # ---- PART 4: dark-matter taxonomy ----
    ("md", "## Part 4 — Dark-matter taxonomy\n"
           "Not all 'organism-dark' compounds are dark for the same reason. Partition them so the "
           "wet-lab priority list distinguishes *where the unknown lives*:\n"
           "- **biosynthesis-known, catabolism-unknown** (`only_biosynthetic_signatures`) — genomes "
           "carry biosynthetic-direction signatures but no catabolic route was found. The chemistry "
           "is made by microbes; what's missing is the *degradation* genetics. **Highest-value "
           "targets** — a catabolic route plausibly exists and is discoverable.\n"
           "- **KEGG-linked but no reaction in genomes** (`kegg_no_rxn_in_genomes`) — the compound "
           "maps to KEGG but no mapped reaction appears in any depot genome.\n"
           "- **only generic reactions** (`only_generic_rxns`) — only non-specific reactions matched; "
           "no compound-specific evidence.\n"
           "- **fully orphan** (`no_kegg`) — no KEGG mapping at all; genuinely uncharted chemistry.\n\n"
           "**MIBiG is the external resource to consult** for the biosynthesis-known bucket "
           "(biosynthetic gene clusters); it is *not* queried here — flagged as a pointer so the "
           "claim stays honest and offline-reproducible."),

    ("code",
     "dark = pd.read_csv(DATA / 'compound_organism_dark.tsv', sep='\\t')\n"
     "# review I1: lauric acid was reclassified callable (measured_fitness); drop any compound that\n"
     "# is now callable in master so the dark taxonomy and the callable count stay consistent.\n"
     "still_dark = set(master[~master['callable']]['compound_id'])\n"
     "n_drop = (~dark['compound_id'].isin(still_dark)).sum()\n"
     "dark = dark[dark['compound_id'].isin(still_dark)].copy()\n"
     "print(f'(dropped {n_drop} now-callable compound(s) from the dark set after I1)')\n"
     "BUCKET = {'only_biosynthetic_signatures':'biosynthesis-known/catabolism-unknown',\n"
     "          'kegg_no_rxn_in_genomes':'KEGG-linked/no-reaction-in-genomes',\n"
     "          'only_generic_rxns':'only-generic-reactions',\n"
     "          'no_kegg':'fully-orphan (no KEGG)'}\n"
     "dark['bucket'] = dark['organism_dark_reason'].map(BUCKET).fillna(dark['organism_dark_reason'])\n"
     "dark = dark.merge(master[['compound_id','source_short','npc_pathway']], on='compound_id',\n"
     "                  how='left', suffixes=('','_m'))\n"
     "dark['mibig_consult'] = dark['organism_dark_reason'] == 'only_biosynthetic_signatures'\n"
     "dark.to_csv(DATA / 'dark_matter_taxonomy.tsv', sep='\\t', index=False)\n"
     "print('dark compounds:', len(dark))\n"
     "print('\\nby bucket:')\n"
     "print(dark['bucket'].value_counts().to_string())\n"
     "print('\\nbiosynthesis-known (consult MIBiG) compounds:')\n"
     "bk = dark[dark['mibig_consult']]\n"
     "print(bk[['name','npc_pathway','source_short']].to_string(index=False))"),

    ("code",
     "# source-stratified dark fraction\n"
     "tot_src = master.groupby('source_short')['compound_id'].nunique()\n"
     "dark_src = master[~master['callable']].groupby('source_short')['compound_id'].nunique()\n"
     "frac_src = (dark_src / tot_src * 100).round(0)\n"
     "print('dark fraction by source:')\n"
     "for s in tot_src.index:\n"
     "    print(f'  {s:12s} {int(dark_src.get(s,0))}/{int(tot_src[s])} dark ({frac_src.get(s,0):.0f}%)')\n"
     "# bucket x source\n"
     "bx = dark.groupby(['bucket','source_short']).size().unstack(fill_value=0)\n"
     "print('\\nbucket x source:'); print(bx.to_string())"),

    ("code",
     "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))\n"
     "bc = dark['bucket'].value_counts()\n"
     "colors = ['#b30000','#e34a33','#fc8d59','#fdcc8a'][:len(bc)]\n"
     "ax1.barh(range(len(bc)), bc.values, color=colors, edgecolor='k', linewidth=0.4)\n"
     "ax1.set_yticks(range(len(bc))); ax1.set_yticklabels(bc.index, fontsize=8); ax1.invert_yaxis()\n"
     "for i, v in enumerate(bc.values): ax1.text(v+0.3, i, str(int(v)), va='center', fontsize=9)\n"
     "ax1.set_xlabel('compounds'); ax1.set_title('Dark-matter taxonomy (74 organism-dark compounds)')\n"
     "bxp = bx.reindex(bc.index)\n"
     "bottom = np.zeros(len(bxp))\n"
     "for src, col in [('groundwater','#1f78b4'),('necromass','#33a02c')]:\n"
     "    if src in bxp.columns:\n"
     "        ax2.barh(range(len(bxp)), bxp[src].values, left=bottom, color=col, label=src,\n"
     "                 edgecolor='k', linewidth=0.4)\n"
     "        bottom += bxp[src].values\n"
     "ax2.set_yticks(range(len(bxp))); ax2.set_yticklabels(bxp.index, fontsize=8); ax2.invert_yaxis()\n"
     "ax2.set_xlabel('compounds'); ax2.set_title('Dark bucket by source'); ax2.legend(fontsize=9)\n"
     "fig.tight_layout(); fig.savefig(FIG / '09d_dark_taxonomy.png', dpi=150)\n"
     "print('saved 09d_dark_taxonomy.png'); plt.close(fig)"),

    ("md", "## NB09 summary\n"
           "Four characterizations of the gap, each descriptive given n=9 callable: (1) "
           "bioavailability is a physical ceiling that partly explains low field signal independent "
           "of genetics; (2) catabolic capacity is carried mostly by **specialist** chassis (one "
           "capacity), with a handful of generalists, and every call is catabolic-direction by "
           "construction; (3) where a capacity is callable it tends to be **conserved within a few "
           "genera** rather than scattered; (4) the dark set is not monolithic — the "
           "*biosynthesis-known / catabolism-unknown* compounds (consult MIBiG) are the highest-"
           "value discovery targets, and the dark fraction is high in **both** sources. None of "
           "this changes the headline: most of these compounds remain organism-dark, and that gap "
           "is the deliverable."),

    ("code",
     "print('=== NB09 OUTPUTS ===')\n"
     "for f in ['compound_physicochem.tsv','dark_matter_taxonomy.tsv']:\n"
     "    d = pd.read_csv(DATA / f, sep='\\t'); print(f'  data/{f}: {d.shape}')\n"
     "for f in ['09a_physicochem_callable_dark.png','09a_bioavailability_space.png',\n"
     "          '09b_chassis.png','09c_clade_conservation.png','09d_dark_taxonomy.png']:\n"
     "    print('  figures/' + f, '✓' if (FIG / f).exists() else 'MISSING')"),
]

build_and_run("09_deepening.ipynb", cells, timeout=900)
