from _build import build_and_run

cells = [
    ("md", "# NB07b — Global Environmental Atlas (broad cross-environment arm of deliverable c)\n\n"
           "NB07 covered only the **local SSO field site** (Oak Ridge groundwater, `enigma_coral`). "
           "This notebook extends deliverable (c) to the **broad cross-environment scope** promised in "
           "RESEARCH_PLAN.md, using abundance data we can actually stand behind:\n\n"
           "- **NMDC `kbase.nmdc_arkin`** — terrestrial/aquatic metagenomes (primary). Genus relative "
           "abundance from covstats; per-**sample** environment labels from `nmdc_metadata.biosample_set` "
           "at **two ontology resolutions**: the **ENVO MIxS triad** (env_broad/local/medium) and the "
           "**GOLD ecosystem path** (ecosystem→category→type→subtype→specific). ~94% of samples labeled.\n"
           "- **Planet Microbe** — marine cruise metagenomes (contrast). Per-run genus abundance labeled "
           "by project (Tara/HOT/BATS) and campaign.\n\n"
           "**What this can and cannot say (honesty over coverage).** These datasets contain *no compound "
           "measurements* — so we cannot link a compound to an environment directly. What we *can* do is "
           "ask where the **implicated utilizer genera** (from NB06 `phylo_utilizer_map.tsv`) are more "
           "abundant. That is a **biome proxy**, not a catabolic-activity measurement. Two discovery modes:\n"
           "1. **Enrichment** — is a genus's relative abundance higher in one environment class than "
           "another? (compositional, zero-inflated → reported as effect sizes + an exploratory rank test).\n"
           "2. **Label-free outliers** — rank *all* samples by each genus's abundance and read off what the "
           "top samples are. Robust to sparse/biased labels and surfaces unexpected reservoirs.\n\n"
           "Genus-name overlap with the 86 implicated genera: NMDC 83/86, Planet Microbe 68/86."),

    ("code",
     "import os\n"
     "from dotenv import load_dotenv\n"
     "import pandas as pd, numpy as np\n"
     "import matplotlib\n"
     "matplotlib.use('Agg')\n"
     "import matplotlib.pyplot as plt\n"
     "from pathlib import Path\n"
     "from scipy.stats import mannwhitneyu\n"
     "\n"
     "DATA = Path('../data'); FIG = Path('../figures')\n"
     "pd.set_option('display.max_columns', 60); pd.set_option('display.width', 240)\n"
     "\n"
     "phylo = pd.read_csv(DATA / 'phylo_utilizer_map.tsv', sep='\\t')\n"
     "IMPL = sorted(phylo['genus'].dropna().unique().tolist())\n"
     "print('implicated genera:', len(IMPL))\n"
     "# genus -> implicated-compound context (breadth + pathways), for the synthesis table\n"
     "gctx = (phylo.groupby('genus')\n"
     "        .agg(n_compounds=('name', 'nunique'),\n"
     "             pathways=('npc_pathway', lambda s: ','.join(sorted(set(str(x) for x in s if pd.notna(x))))))\n"
     "        .reset_index())\n"
     "print(gctx.head().to_string(index=False))"),

    ("code",
     "load_dotenv('/home/aparkin/BERIL-research-observatory/.env')\n"
     "_tok = os.environ['KBASE_AUTH_TOKEN']\n"
     "from pyspark.sql import SparkSession, functions as F\n"
     "_url = f'sc://jupyter-aparkin.jupyterhub-prod:15002/;use_ssl=false;x-kbase-token={_tok}'\n"
     "spark = SparkSession.builder.remote(_url).getOrCreate()\n"
     "print('spark up')"),

    ("md", "## Arm A — NMDC genus relative abundance with sample-level environment labels\n"
           "Relative abundance currency: per covstats `file_id`, genus `total_tpm` divided by the file's "
           "summed `total_tpm` (fraction among classified genera). Each `file_id` is one community "
           "observation. Two label sets joined per sample from `biosample_set` (exact `id` join, no "
           "version mismatch): ENVO `env_medium`/`env_broad` and GOLD `ecosystem_type`."),

    ("code",
     "# --- relative abundance for implicated genera (present rows only) ---\n"
     "roll = spark.table('kbase.nmdc_arkin.covstats_taxonomy_rollup')\n"
     "file_tot = roll.groupBy('file_id').agg(F.sum('total_tpm').alias('file_tpm'))\n"
     "imp = roll.filter(F.col('genus').isin(IMPL)).select('file_id', 'genus', 'total_tpm')\n"
     "relab = (imp.join(file_tot, 'file_id')\n"
     "         .withColumn('relab', F.col('total_tpm') / F.col('file_tpm'))\n"
     "         .select('file_id', 'genus', 'relab'))\n"
     "pres = relab.toPandas()\n"
     "print('present (genus x file) rows:', len(pres), '| distinct files:', pres['file_id'].nunique())"),

    ("code",
     "# --- denominator = the covstats files that actually carry taxonomy (NOT all 6700 lookup rows) ---\n"
     "# one row per taxonomy-bearing file, labeled with TWO ontology sets from biosample_set.\n"
     "# NOTE: one covstats file (assembly) can link to several biosample ids; we keep one label/file.\n"
     "roll_files = file_tot.select('file_id')\n"
     "sfl = (spark.table('kbase.nmdc_arkin.sample_file_lookup')\n"
     "       .select(F.col('covstats_file_id').alias('file_id'), 'sample_id').distinct())\n"
     "bs = (spark.table('nmdc_metadata.biosample_set')\n"
     "      .select(F.col('id').alias('sample_id'),\n"
     "              'ecosystem', 'ecosystem_category', 'ecosystem_type',\n"
     "              'ecosystem_subtype', 'specific_ecosystem',\n"
     "              'env_broad_scale_term_name', 'env_local_scale_term_name', 'env_medium_term_name',\n"
     "              'lat_lon_latitude', 'lat_lon_longitude', 'depth_has_numeric_value')\n"
     "      .dropDuplicates(['sample_id']))\n"
     "uni = (roll_files.join(sfl, 'file_id', 'left').join(bs, 'sample_id', 'left')\n"
     "       .dropDuplicates(['file_id']).toPandas())\n"
     "print('taxonomy-bearing files (denominator):', len(uni))\n"
     "for c in ['env_medium_term_name', 'env_broad_scale_term_name', 'ecosystem_type']:\n"
     "    print(f'  labeled [{c}]:', uni[c].notna().sum())"),

    ("code",
     "# --- macro env-class from ENVO env_medium (fallback to GOLD ecosystem_type) ---\n"
     "def macro(med, eco):\n"
     "    s = (str(med) if pd.notna(med) else (str(eco) if pd.notna(eco) else '')).lower()\n"
     "    if not s: return 'unlabeled'\n"
     "    if any(k in s for k in ['periphyt', 'epilith', 'epipsamm', 'epiphyt', 'biofilm', 'microbial mat']): return 'periphyton'\n"
     "    if 'sediment' in s: return 'sediment'\n"
     "    if 'soil' in s: return 'soil'\n"
     "    if any(k in s for k in ['rhizosphere', 'root', 'phyllosphere', 'plant', 'litter', 'leaf']): return 'plant'\n"
     "    if any(k in s for k in ['fecal', 'feces', 'gut', 'host', 'rumen', 'oral']): return 'host'\n"
     "    if any(k in s for k in ['marine', 'ocean', 'sea water', 'seawater', 'saline', 'estuar']): return 'marine'\n"
     "    if any(k in s for k in ['lake', 'fresh', 'river', 'pond', 'stream', 'groundwater', 'aquifer', 'surface water']): return 'freshwater'\n"
     "    if 'water' in s: return 'water_other'\n"
     "    return 'other'\n"
     "uni['macro_env'] = [macro(m, e) for m, e in zip(uni['env_medium_term_name'], uni['ecosystem_type'])]\n"
     "print(uni['macro_env'].value_counts().to_string())\n"
     "# --- IMPORTANT: covstats rollup is per-SPECIES; sum species->genus per file before any max/outlier ---\n"
     "presg = pres.groupby(['file_id', 'genus'], as_index=False)['relab'].sum()\n"
     "presg = presg.merge(uni, on='file_id', how='left')\n"
     "print('genus-aggregated (genus x file) rows:', len(presg))"),

    ("md", "## Arm A enrichment — abundance by environment class\n"
           "For every (genus, macro-env) we report prevalence (fraction of class samples where the genus is "
           "detected), mean relative abundance **over all class samples** (genus-absent counted as 0, the "
           "honest compositional summary), and mean among detections. We then rank-test **soil vs "
           "freshwater** (the two best-powered terrestrial classes) per genus. Compositional zero-inflated "
           "data → treat p-values as exploratory; lead with effect sizes."),

    ("code",
     "N_class = uni.groupby('macro_env')['file_id'].nunique().to_dict()\n"
     "g = (presg.dropna(subset=['macro_env'])\n"
     "     .groupby(['genus', 'macro_env'])\n"
     "     .agg(n_present=('file_id', 'nunique'), sum_relab=('relab', 'sum'),\n"
     "          mean_present=('relab', 'mean'), max_relab=('relab', 'max')).reset_index())\n"
     "g['n_class'] = g['macro_env'].map(N_class)\n"
     "g['prevalence'] = g['n_present'] / g['n_class']\n"
     "g['mean_relab_all'] = g['sum_relab'] / g['n_class']\n"
     "g = g.drop(columns='sum_relab')\n"
     "# the substantively interesting classes\n"
     "MAIN = ['soil', 'freshwater', 'sediment', 'plant', 'host', 'periphyton', 'marine']\n"
     "show = (g[g['macro_env'].isin(MAIN)]\n"
     "        .sort_values('mean_relab_all', ascending=False).head(20))\n"
     "print('top genus x env by mean relative abundance (all-sample):')\n"
     "print(show[['genus', 'macro_env', 'n_present', 'n_class', 'prevalence', 'mean_relab_all', 'max_relab']]\n"
     "      .to_string(index=False, float_format=lambda x: f'{x:.4g}'))"),

    ("code",
     "# soil vs freshwater rank test per genus (zeros included over class universe)\n"
     "soil_files = uni.loc[uni['macro_env'] == 'soil', 'file_id'].tolist()\n"
     "fw_files   = uni.loc[uni['macro_env'] == 'freshwater', 'file_id'].tolist()\n"
     "pv = presg.pivot_table(index='file_id', columns='genus', values='relab', aggfunc='sum', fill_value=0.0)\n"
     "def vec(files, genus):\n"
     "    idx = pv.index.intersection(files)\n"
     "    base = pd.Series(0.0, index=files)\n"
     "    if genus in pv.columns:\n"
     "        base.loc[idx] = pv.loc[idx, genus]\n"
     "    return base.values\n"
     "rows = []\n"
     "for gen in IMPL:\n"
     "    a, b = vec(soil_files, gen), vec(fw_files, gen)\n"
     "    if (a > 0).sum() + (b > 0).sum() < 5:  # too sparse to test\n"
     "        continue\n"
     "    try:\n"
     "        u, p = mannwhitneyu(a, b, alternative='two-sided')\n"
     "    except ValueError:\n"
     "        continue\n"
     "    ms, mf = a.mean(), b.mean()\n"
     "    rows.append((gen, ms, mf, np.log2((ms + 1e-9) / (mf + 1e-9)),\n"
     "                 (a > 0).mean(), (b > 0).mean(), p))\n"
     "enr = pd.DataFrame(rows, columns=['genus', 'mean_soil', 'mean_fresh', 'log2_soil_fresh',\n"
     "                                  'prev_soil', 'prev_fresh', 'p'])\n"
     "# BH correction\n"
     "enr = enr.sort_values('p').reset_index(drop=True)\n"
     "m = len(enr); enr['q'] = (enr['p'] * m / (enr.index + 1)).clip(upper=1.0)\n"
     "enr['q'] = enr['q'][::-1].cummin()[::-1]\n"
     "print(f'genera tested soil vs freshwater: {m} (n_soil={len(soil_files)}, n_fresh={len(fw_files)})')\n"
     "print('\\nstrongest soil-enriched (log2>0, q<0.05):')\n"
     "print(enr[(enr['log2_soil_fresh'] > 0) & (enr['q'] < 0.05)].head(12)\n"
     "      .to_string(index=False, float_format=lambda x: f'{x:.3g}'))\n"
     "print('\\nstrongest freshwater-enriched (log2<0, q<0.05):')\n"
     "print(enr[(enr['log2_soil_fresh'] < 0) & (enr['q'] < 0.05)].sort_values('log2_soil_fresh').head(12)\n"
     "      .to_string(index=False, float_format=lambda x: f'{x:.3g}'))"),

    ("md", "## Arm B — label-free outlier samples\n"
           "For each implicated genus, the samples where it is most abundant — regardless of label. These "
           "are candidate environmental reservoirs of the genus (and, by NB06 linkage, of its compound "
           "associations). We read off each outlier's ENVO + GOLD labels and coordinates so unexpected "
           "habitats surface even where structured labels are missing."),

    ("code",
     "TOPN = 3\n"
     "out_rows = []\n"
     "for gen, sub in presg.groupby('genus'):\n"
     "    top = sub.sort_values('relab', ascending=False).head(TOPN)\n"
     "    for _, r in top.iterrows():\n"
     "        out_rows.append((gen, r['relab'], r['sample_id'], r['macro_env'],\n"
     "                         r['env_medium_term_name'], r['env_broad_scale_term_name'],\n"
     "                         r['ecosystem_type'], r['specific_ecosystem'],\n"
     "                         r['lat_lon_latitude'], r['lat_lon_longitude']))\n"
     "outl = pd.DataFrame(out_rows, columns=['genus', 'relab', 'sample_id', 'macro_env',\n"
     "                    'env_medium', 'env_broad', 'gold_ecosystem_type', 'gold_specific',\n"
     "                    'lat', 'lon'])\n"
     "outl = outl.sort_values('relab', ascending=False).reset_index(drop=True)\n"
     "print('global top outlier (genus, sample) by relative abundance:')\n"
     "print(outl.head(20)[['genus', 'relab', 'macro_env', 'env_medium', 'gold_ecosystem_type', 'lat', 'lon']]\n"
     "      .to_string(index=False, float_format=lambda x: f'{x:.3g}'))\n"
     "print('\\nwhere do the strongest single-genus spikes live? (macro_env of each genus top hit)')\n"
     "best = outl.sort_values('relab', ascending=False).drop_duplicates('genus')\n"
     "print(best['macro_env'].value_counts().to_string())"),

    ("md", "## Arm C — Planet Microbe marine contrast\n"
           "Per-run genus abundance from `run_to_taxonomy.abundance` (already relative), labeled by project "
           "and campaign. 302 marine runs with taxonomy. This is the saltwater counterpoint to the "
           "terrestrial/freshwater NMDC arm."),

    ("code",
     "# IMPORTANT: PM taxonomy.name is mostly SPECIES-level ('Sphingomonas panacis'); the genus-rank\n"
     "# reference entries carry ~0 abundance. Extract genus = first token, then sum species->genus per run.\n"
     "rt = (spark.table('planetmicrobe.planetmicrobe.run_to_taxonomy')\n"
     "      .select('run_id', 'tax_id', 'abundance'))\n"
     "taxg = (spark.table('planetmicrobe.planetmicrobe.taxonomy')\n"
     "        .withColumn('genus', F.split(F.col('name'), ' ').getItem(0))\n"
     "        .select('tax_id', 'genus'))\n"
     "rtg = (rt.join(taxg, 'tax_id').filter(F.col('genus').isin(IMPL))\n"
     "       .groupBy('run_id', 'genus').agg(F.sum('abundance').alias('abundance')))\n"
     "run = spark.table('planetmicrobe.planetmicrobe.run').select('run_id', 'experiment_id')\n"
     "exp = spark.table('planetmicrobe.planetmicrobe.experiment').select('experiment_id', 'sample_id')\n"
     "p2s = spark.table('planetmicrobe.planetmicrobe.project_to_sample').select('project_id', 'sample_id')\n"
     "proj = spark.table('planetmicrobe.planetmicrobe.project').select('project_id', F.col('name').alias('project'))\n"
     "s2e = spark.table('planetmicrobe.planetmicrobe.sample_to_sampling_event').select('sample_id', 'sampling_event_id')\n"
     "se = spark.table('planetmicrobe.planetmicrobe.sampling_event').select('sampling_event_id', 'campaign_id')\n"
     "camp = spark.table('planetmicrobe.planetmicrobe.campaign').select('campaign_id', F.col('name').alias('campaign'))\n"
     "labels = (run.join(exp, 'experiment_id')\n"
     "          .join(p2s, 'sample_id', 'left').join(proj, 'project_id', 'left')\n"
     "          .join(s2e, 'sample_id', 'left').join(se, 'sampling_event_id', 'left')\n"
     "          .join(camp, 'campaign_id', 'left')\n"
     "          .select('run_id', 'project', 'campaign').dropDuplicates(['run_id']))\n"
     "pmdf = rtg.join(labels, 'run_id', 'left').select('run_id', 'genus', 'abundance', 'project', 'campaign').toPandas()\n"
     "n_runs_pm = spark.table('planetmicrobe.planetmicrobe.run_to_taxonomy').select('run_id').distinct().count()\n"
     "# abundance is a real 0-1 fraction but zero-inflated; separate 'listed in run' from 'positive abundance'\n"
     "pmdf['present'] = pmdf['abundance'] > 0\n"
     "print('PM implicated-genus (run x genus) rows:', len(pmdf), '| runs w/ taxonomy:', n_runs_pm)\n"
     "pm_g = (pmdf.groupby('genus')\n"
     "        .agg(n_runs_listed=('run_id', 'nunique'),\n"
     "             n_runs_pos=('present', 'sum'),\n"
     "             mean_abund=('abundance', 'mean'),\n"
     "             max_abund=('abundance', 'max')).reset_index())\n"
     "pm_g['prevalence_pos'] = pm_g['n_runs_pos'] / n_runs_pm\n"
     "print('\\ntop implicated genera in marine (Planet Microbe), by mean abundance:')\n"
     "print(pm_g.sort_values('mean_abund', ascending=False).head(15)\n"
     "      .to_string(index=False, float_format=lambda x: f'{x:.3e}'))\n"
     "print('\\nMagnitude note: most implicated (terrestrial/freshwater) genera are detectable but')\n"
     "print('low in open-ocean runs (~1e-3 to 1e-4); a few genuine marine members (e.g. Alteromonas)')\n"
     "print('reach ~1e-2. So marine is mostly a NEGATIVE biome contrast, with marine-native exceptions.')\n"
     "print('\\nby project:')\n"
     "print(pmdf['project'].value_counts().head(8).to_string())"),

    ("md", "## Arm D — synthesis: the global environmental atlas\n"
           "One long-format table: every implicated genus × environment class × source, with prevalence and "
           "abundance. NMDC supplies terrestrial/freshwater/sediment/plant/host classes; Planet Microbe "
           "supplies a marine class. Joined to NB06 compound/pathway context per genus."),

    ("code",
     "# NMDC long rows (main classes only)\n"
     "nmdc_atlas = g[g['macro_env'].isin(MAIN)][['genus', 'macro_env', 'n_present', 'n_class',\n"
     "             'prevalence', 'mean_relab_all', 'mean_present', 'max_relab']].copy()\n"
     "nmdc_atlas['source'] = 'NMDC'\n"
     "nmdc_atlas = nmdc_atlas.rename(columns={'macro_env': 'env_class', 'mean_relab_all': 'mean_relab'})\n"
     "# PM marine rows (n_present = runs with POSITIVE abundance, not merely listed)\n"
     "pm_atlas = pm_g.rename(columns={'mean_abund': 'mean_relab', 'max_abund': 'max_relab',\n"
     "                                'n_runs_pos': 'n_present', 'prevalence_pos': 'prevalence'}).copy()\n"
     "pm_atlas['env_class'] = 'marine'; pm_atlas['source'] = 'PlanetMicrobe'\n"
     "pm_atlas['n_class'] = n_runs_pm; pm_atlas['mean_present'] = pm_atlas['mean_relab']\n"
     "cols = ['genus', 'env_class', 'source', 'n_present', 'n_class', 'prevalence',\n"
     "        'mean_relab', 'mean_present', 'max_relab']\n"
     "atlas = pd.concat([nmdc_atlas[cols], pm_atlas[cols]], ignore_index=True)\n"
     "atlas = atlas.merge(gctx, on='genus', how='left')\n"
     "atlas = atlas.sort_values(['genus', 'mean_relab'], ascending=[True, False]).reset_index(drop=True)\n"
     "atlas.to_csv(DATA / 'env_atlas_global.tsv', sep='\\t', index=False)\n"
     "print('wrote data/env_atlas_global.tsv', atlas.shape)\n"
     "# enrichment + outliers as companion tables\n"
     "enr.merge(gctx, on='genus', how='left').to_csv(DATA / 'env_enrichment_soil_fresh.tsv', sep='\\t', index=False)\n"
     "outl.merge(gctx, on='genus', how='left').to_csv(DATA / 'env_outlier_samples.tsv', sep='\\t', index=False)\n"
     "print('wrote data/env_enrichment_soil_fresh.tsv', enr.shape)\n"
     "print('wrote data/env_outlier_samples.tsv', outl.shape)"),

    ("code",
     "# Figure 1: genus x env-class mean relative-abundance heatmap (top genera by overall signal)\n"
     "mat = atlas.pivot_table(index='genus', columns='env_class', values='mean_relab', aggfunc='max', fill_value=0)\n"
     "order_classes = [c for c in ['soil', 'freshwater', 'sediment', 'plant', 'host', 'periphyton', 'marine'] if c in mat.columns]\n"
     "mat = mat[order_classes]\n"
     "top_g = mat.max(axis=1).sort_values(ascending=False).head(30).index\n"
     "mat = mat.loc[top_g]\n"
     "fig, ax = plt.subplots(figsize=(7, 9))\n"
     "im = ax.imshow(np.log10(mat.values + 1e-5), aspect='auto', cmap='viridis')\n"
     "ax.set_xticks(range(len(mat.columns))); ax.set_xticklabels(mat.columns, rotation=45, ha='right')\n"
     "ax.set_yticks(range(len(mat.index))); ax.set_yticklabels(mat.index, fontsize=8)\n"
     "ax.set_title('Implicated utilizer genera: mean relative abundance by environment\\n(log10, NMDC + Planet Microbe)')\n"
     "cb = fig.colorbar(im, ax=ax, shrink=0.6); cb.set_label('log10 mean relative abundance')\n"
     "fig.tight_layout(); fig.savefig(FIG / '07b_env_atlas_heatmap.png', dpi=150); plt.close(fig)\n"
     "print('saved 07b_env_atlas_heatmap.png', mat.shape)"),

    ("code",
     "# Figure 2: soil-vs-freshwater enrichment volcano-ish (effect size vs significance)\n"
     "fig, ax = plt.subplots(figsize=(7, 6))\n"
     "sig = enr['q'] < 0.05\n"
     "ax.scatter(enr.loc[~sig, 'log2_soil_fresh'], -np.log10(enr.loc[~sig, 'p'] + 1e-300),\n"
     "           c='#bbbbbb', s=18, label='q>=0.05')\n"
     "ax.scatter(enr.loc[sig, 'log2_soil_fresh'], -np.log10(enr.loc[sig, 'p'] + 1e-300),\n"
     "           c='#d7301f', s=26, label='q<0.05')\n"
     "for _, r in enr[sig].sort_values('p').head(10).iterrows():\n"
     "    ax.annotate(r['genus'], (r['log2_soil_fresh'], -np.log10(r['p'] + 1e-300)),\n"
     "                fontsize=7, xytext=(3, 3), textcoords='offset points')\n"
     "ax.axvline(0, color='k', lw=0.6)\n"
     "ax.set_xlabel('log2(mean relab soil / freshwater)   <-fresh  | soil->')\n"
     "ax.set_ylabel('-log10 p (Mann-Whitney, exploratory)')\n"
     "ax.set_title('Implicated genera: soil vs freshwater differential abundance (NMDC)')\n"
     "ax.legend(fontsize=8)\n"
     "fig.tight_layout(); fig.savefig(FIG / '07b_soil_fresh_enrichment.png', dpi=150); plt.close(fig)\n"
     "print('saved 07b_soil_fresh_enrichment.png')"),

    ("code",
     "print('=' * 64)\n"
     "print('NB07b GLOBAL ENVIRONMENTAL ATLAS — HEADLINE')\n"
     "print('=' * 64)\n"
     "print(f'implicated genera queried           : {len(IMPL)}')\n"
     "print(f'NMDC taxonomy-bearing metagenomes   : {len(uni)} (denominator = covstats files w/ taxonomy)')\n"
     "print(f'NMDC genera detected                : {presg[\"genus\"].nunique()}  '\n"
     "      f'(in {presg[\"file_id\"].nunique()} metagenomes)')\n"
     "lab = uni[uni[\"macro_env\"] != \"unlabeled\"][\"file_id\"].nunique()\n"
     "print(f'NMDC samples with env label         : {lab}/{len(uni)} '\n"
     "      f'({100*lab/len(uni):.0f}%, two ontologies: ENVO triad + GOLD path)')\n"
     "pm_pos = int((pm_g[\"n_runs_pos\"] > 0).sum())\n"
     "print(f'PM (marine) genera w/ positive abund: {pm_pos}/{pmdf[\"genus\"].nunique()} listed  (in {n_runs_pm} runs)')\n"
     "n_sig = int((enr['q'] < 0.05).sum())\n"
     "print(f'soil-vs-freshwater genera tested     : {len(enr)}; q<0.05: {n_sig} (exploratory)')\n"
     "print('\\nCAVEATS (carried into the report):')\n"
     "print('  - No compound measurements in any env dataset -> genus abundance is a BIOME PROXY,')\n"
     "print('    not catabolic activity. Enrichment != the genus degrades the compound there.')\n"
     "print('  - Relative abundance is compositional & zero-inflated; rank-test p-values exploratory.')\n"
     "print('  - PM marine arm is small (302 runs) and gene-content-blind; presence/abundance only.')\n"
     "print('  - Outlier mode (Arm B) is label-robust and the most defensible discovery signal.')\n"
     "spark.stop()\n"
     "print('\\nspark stopped; NB07b complete')"),
]

build_and_run("07b_environmental_atlas_global.ipynb", cells, timeout=3000)
