"""Additive registry resolution (the apply-side of ``registry.yaml``).

The global registry maps raw per-project entity/topic slugs to canonical keys via aliases. It is
ADDITIVE and never destructive: an unknown slug passes through unchanged. ``registry.yaml`` is
generated by an LLM reconcile skill; this module is the deterministic lookup that ``plan`` consults.
"""

from __future__ import annotations

from pathlib import Path

import yaml


class Registry:
    """Resolve raw entity/topic slugs to canonical registry keys (case-insensitive)."""

    def __init__(self, raw: dict):
        self._entities: dict[str, str] = {}
        for key, spec in (raw.get("entities") or {}).items():
            # Canonical key wins its own name; other aliases are first-wins.
            self._entities[key.casefold()] = key
            for alias in spec.get("aliases", []):
                self._entities.setdefault(alias.casefold(), key)
        self._topics: dict[str, str] = {
            key.casefold(): key for key in (raw.get("topics") or {})
        }

    def entity_key(self, slug: str) -> str:
        """Return the canonical entity key for ``slug``, or ``slug`` unchanged if unknown."""
        return self._entities.get(slug.casefold(), slug)

    def topic_key(self, slug: str) -> str:
        """Return the canonical topic key for ``slug``, or ``slug`` unchanged if unknown."""
        return self._topics.get(slug.casefold(), slug)

    @classmethod
    def from_yaml(cls, path) -> "Registry":
        """Load a ``Registry`` from a ``registry.yaml`` file."""
        raw = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
        return cls(raw)
