"""Additive registry resolution (the apply-side of ``registry.yaml``).

The global registry maps raw per-project entity/topic slugs to canonical keys via aliases. It is
ADDITIVE and never destructive: an unknown slug passes through unchanged. ``registry.yaml`` is
generated by an LLM reconcile skill; this module is the deterministic lookup that ``plan`` consults.
"""

from __future__ import annotations

from pathlib import Path

import yaml


class Registry:
    """Resolve raw entity/topic slugs to canonical registry keys (case-insensitive)."""

    def __init__(self, raw: dict):
        self._entities = _alias_map(raw.get("entities"))
        self._topics = _alias_map(raw.get("topics"))

    def entity_key(self, slug: str) -> str:
        """Return the canonical entity key for ``slug``, or ``slug`` unchanged if unknown."""
        return self._entities.get(slug.casefold(), slug)

    def topic_key(self, slug: str) -> str:
        """Return the canonical topic key for ``slug``, or ``slug`` unchanged if unknown."""
        return self._topics.get(slug.casefold(), slug)

    @classmethod
    def from_yaml(cls, path) -> "Registry":
        """Load a ``Registry`` from a ``registry.yaml`` file."""
        raw = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
        return cls(raw)


def _alias_map(section: dict | None) -> dict[str, str]:
    """Build a case-folded alias->canonical map. Canonical name wins; aliases are first-wins."""
    resolved: dict[str, str] = {}
    for key, spec in (section or {}).items():
        resolved[key.casefold()] = key
        for alias in (spec or {}).get("aliases", []):
            resolved.setdefault(alias.casefold(), key)
    return resolved
